### DISCUSSION TITLE
Handling repeated query params in query string

### DISCUSSION THREAD

**Discussion by pleshakov** [kubernetes-sigs/gateway-api#1269] [General]
Hello folks! For a query string  `?a=1&a=2`  and the following matches in an HTTPRoute:
(1)
```yaml
queryParams:
- name: a
  value: "1"
```
(2)

```yaml
queryParams:
- name: a
  value: "2"
```
Should (1) match?
Should (2) match?

I wonder what the expected behavior is. 

Notes:
- the confirmance tests do not test for that case -- https://github.com/kubernetes-sigs/gateway-api/blob/5af4606ca9cc0e46c30f558136144321f276bc2a/conformance/tests/httproute-query-param-matching.go#L47-L80
- the query param doc doesn't seem to describe that case -- https://github.com/kubernetes-sigs/gateway-api/blob/5af4606ca9cc0e46c30f558136144321f276bc2a/apis/v1beta1/httproute_types.go#L408

Cheers
