### DISCUSSION TITLE
Questions about HTTPRequestRedirectFilter

### DISCUSSION THREAD

**Discussion by pleshakov** [kubernetes-sigs/gateway-api#1360] [Q&A] [answered]
Hi,

I've got a few questions about the HTTPRequestRedirectFilter behavior. I wonder if there are some guidelines around that  behavior.

(1) 
In the example here https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#redirects  we have:

```yaml
. . .
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
      backendRefs:
      - name: example-svc
        weight: 1
        port: 80
```
where one backendRef is configured. However, since the redirect is not conditional, the data plane will never proxy to the backend -- it will always redirect.

That brings a few questions:

(a) Should a Gateway implementation report to the user that the backendRefs will be ignored?

(b) Considering that a Gateway implementation will ignore the backendRefs, should it validate the backendRefs? For example, insure that the backend service exists? Or can a Gateway implementation skip the validation of ignored backendRefs?

(c) Is it necessary to have the backendRefs? Would it make sense to remove them from the example?

(2) 
For a few fields in `HTTPRequestRedirectFilter` , there is a validation requirement like below:
```
	//
	// Unknown values here must result in the implementation setting the
	// Attached Condition for the Route to `status: False`, with a
	// Reason of `UnsupportedValue`.
```
(from https://github.com/kubernetes-sigs/gateway-api/blob/v0.5.0/apis/v1beta1/httproute_types.go#L829-L831)

(a) If a Gateway implementation finds that a field is invalid in an HTTPRequestRedirectFilter and  it sets Attached Condition for the Route to `status: False` , does this mean all routing rules in the route will be ignored  or just the affected rule? 

(b) What status code the data plane shall return?
