### DISCUSSION TITLE
TCP specification question

### DISCUSSION THREAD

**Discussion by ivanmatmati** [kubernetes-sigs/gateway-api#1434] [Q&A]
Hi,
I would like to ask two questions about Gateway API specification for TCP protocol.

1.  The specification says that to determine which route is selected when multiple can apply we should select by these rules:

    * The most specific match as defined by the Route type.
    * The oldest Route based on creation timestamp. For example, a Route with
      a creation timestamp of "2020-09-08 01:02:03" is given precedence over
      a Route with a creation timestamp of "2020-09-08 01:02:04".
     * If everything else is equivalent, the Route appearing first in
	alphabetical order (namespace/name) should be given precedence. For
	example, foo/bar is given precedence over foo/baz.

    Could you explain the rationale behind the timestamp and alphabetical ordering of route ?
    I can think of situations where it could be annoying. For example, if I want to insert a route as first choice considering the creation timestamp criteria I guess I should recreate all routes timely ordered.
    Same with alphabetical ordering which can even be impossible if naming convention is present.
2. Suppose two gateways have each a listener on TCP port 8000. Is it forbidden ? Specification does not say if so but I guess it should be because grouping with TCP seems impossible. Am I missing something ?

**Comment by shaneutt** [comment]
> Could you explain the rationale behind the timestamp and alphabetical ordering of route?

The short answer is that this is the best we had at the time that was met with general consensus by contributors and there hasn't been significant enough pressure since then to change it. Keep in mind the conflict guidance was written in 2020, it is definitely on the table to discuss alternatives and the weekly community sync might be a good place to do that.

> Suppose two gateways have each a listener on TCP port 8000. Is it forbidden ? Specification does not say if so but I guess it should be because grouping with TCP seems impossible. Am I missing something?

Do you mean two separate `Gateways` each with a port `8000` listener on the _same_ address, or could you elaborate on this further please?

**Reply by ivanmatmati** [reply]
The example would be something like:
```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: gw1
  namespace: ns1
spec:
  gatewayClassName: gwc
  listeners:
  - name: listener1
    protocol: TCP
    port: 8000
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: gw2
  namespace: ns2
spec:
  gatewayClassName: gwc
  listeners:
  - name: listener2
    protocol: TCP
    port: 8000
```
I assume the set of addresses will be the same. We will end up with TCP port 8000 tried to be bound two times on same address(es).
As this is TCP we can't expect path matching, hostname or whatever to differentiate the routing so it seems impossible to group the listeners.
The result for TCP is that it doesn't make sense to permit this submission.
And the following rule only applies to listeners in the same gateway  :

- If this field specifies multiple Listeners that have the same Port value but are not compatible, the implementation must raise a "Conflicted" condition in the Listener status.

This rule is laking its interpretation at multiple gateways level. To my eyes the repetition of listener port for gateways should be forbidden for TCP. Without this clarification, it's not clear if an implementation should support this combination or not with TCP.
