### DISCUSSION TITLE
Ideas around reporting Policy configuration in Route Status

### DISCUSSION THREAD

**Discussion by sunjayBhatia** [kubernetes-sigs/gateway-api#1531] [Ideas]
These ideas could be used by the upstream project itself to provide a mechanism for implementers of the Gateway API.
This is mostly an exercise in seeing if it is feasible to do something in this space, and what solutions could look like.

The suggestions here may be combined or used separately where appropriate.

---

Add the "effective policy configuration" to the `RouteParentStatus` type.
This is an effort to signify the applied policies flow down from individual Gateway hierarchies, especially given Routes may be attached to different Gateways.
We could go with an approach that does not include this information under `RouteParentStatus`, but would need to then duplicate some of the fields from this struct, namely `controllerName` to ensure we know which controller handled the Policy and set the configuration.

```go
type RouteParentStatus struct {
	...

	// EffectivePolicyConfigurations is a list of policies in effect on this
	// Route.
	//
	// +optional
	EffectivePolicyConfigurations []RouteEffectivePolicyConfiguration `json:"effectivePolicyConfigurations"`
}

type RouteEffectivePolicyConfiguration struct {
	PolicyType PolicyGroupKind `json:"policyType"`

	SectionName SectionName `json:"sectionName"`

	PolicyValue string `json:"policyValue"`
}

// PolicyGroupKind indicates the group and kind of a Policy resource.
type PolicyGroupKind struct {
	// Group is the group of the Policy.
	Group Group `json:"group,omitempty"`

	// Kind is the kind of the Route.
	Kind Kind `json:"kind"`
}
```

A possible resulting Status example:

```yaml
...
status:
  parents:
  - conditions:
    - lastTransitionTime: "2022-11-07T20:27:56Z"
      message: Accepted HTTPRoute
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    controllerName: projectcontour.io/projectcontour/contour
    effectivePolicyConfigurations:
    - policyType:
        group: projectcontour.io
        kind: RateLimitPolicy
      policyValue: '{"requests":10,"unit":"minute","responseStatusCode":503}'
      sectionName: unsupportedfornow
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: example
      namespace: demo
```

This follows [this spike](https://github.com/sunjayBhatia/contour/commit/caa275a337486fdb6fed6e329ed9b63edc2569ad) and included example YAML for HTTPRoutes and RateLimitPolicies.
It uses [this spike on the Gateway API](https://github.com/sunjayBhatia/gateway-api/commit/3a96f4e00fc947d82f1c3d8e6d0b6e1aef577d36).
Here we've also added the `sectionName` field which could be used if `PolicyTargetReference` supports it in the future and the value would the name of the `HTTPRouteRule` this final Policy applies to.
The `policyValue` is just marshalled JSON from the RateLimitPolicy for simplicity in this example.
The values here represent the combination of a Policy applied to a Gateway and the Policy applied to the HTTPRoute this Status is set on.

---

Rather than using a structured type to represent the kind of Policy that is in effect, we could use a type usable as a map key.
This would ensure one effective Policy is set per kind.
See [Contour spike](https://github.com/sunjayBhatia/contour/commit/fa7282d93e9f74eaf83bfd558c395ae096c7b939) and [Gateway API changes](https://github.com/sunjayBhatia/gateway-api/commit/0cf3fa56af687329d5aeb7fd1eadfe835c75269b)

```go
type RouteEffectivePolicyConfiguration struct {
	PolicyType string `json:"policyType"`
  ...
}
```

Resulting in Status:

```yaml
status:
  parents:
  - ...
    controllerName: projectcontour.io/projectcontour/contour
    effectivePolicyConfigurations:
    - policyType: projectcontour.io/RateLimitPolicy
      policyValue: '{"requests":10,"unit":"minute","responseStatusCode":503}'
      sectionName: unsupportedfornow
    - policyType: projectcontour.io/AuthorizationPolicy
      policyValue: ...
      sectionName: unsupportedfornow
    ...
```

---

Expressing the actual value of the Policy settings in Status is a bit complicated.
One way could be to introduce a `PolicySettings` list, that would allow us to show individual field settings and what Policy resource they came from.
We can again use the `field` name as a unique key to use as a map key for some validation.

```go
type RouteEffectivePolicyConfiguration struct {
	...

	// +listType=map
	// +listMapKey=field
	PolicySettings []PolicySetting `json:"policySettings"`
}

type PolicySetting struct {
	Field string `json:"field"`

	Value string `json:"value"`

	PolicyName string `json:"policyName"`
}
```

See example Status below.

```yaml
status:
  parents:
  - conditions:
    - lastTransitionTime: "2022-11-11T01:44:12Z"
      message: Accepted HTTPRoute
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    controllerName: projectcontour.io/projectcontour/contour
    effectivePolicyConfigurations:
    - policySettings:
      - field: local.requests
        policyName: local-ratelimit-config-route
        value: "2"
      - field: local.unit
        policyName: local-ratelimit-config-route
        value: minute
      - field: local.responseStatusCode
        policyName: local-ratelimit-config-gw
        value: "503"
    ...
```

Here we can see a field has been set by the Policy targeting the Gateway and others set by the Policy targeting the HTTPRoute itself.

This approach as a few upsides, since it offers a lot of visibility into fields, values, and what resources they were configured in.
However, it is a bit complicated and can definitely become unwieldy if a Policy resource grows to contain many fields or any significant nested structure.

See [Contour spike](https://github.com/sunjayBhatia/contour/commit/ff49ae7edaf7f8b705f8a3d5f95e8a6b39f286f9) and [Gateway API spike](https://github.com/sunjayBhatia/gateway-api/commit/20e2f70ba9cd190d62f1234c116c90d66d3ba0aa).

---

Instead of expressing the values specified by a hierarchy of Policies in Status directly, we could instead have the controller implementing the Route and applying Policies simply add a reference to a *new* Policy generated with the resulting values.

We would add to the `RouteParentStatus` (or other location):

```go
type RouteParentStatus struct {
  ...

	EffectivePolicyConfigurationReferences []LocalObjectReference `json:"effectivePolicyConfigRefs"`
}
```

These would be a list of references to Policy objects that were generated to express what Policy values are actually in effect, given the defaults and overrides applied.
There could be some validation that the group/kind/name of these weren't repeated.

Some example status:

```yaml
status:
  parents:
  - conditions:
    - lastTransitionTime: "2022-11-11T01:44:12Z"
      message: Accepted HTTPRoute
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    controllerName: projectcontour.io/projectcontour/contour
    effectivePolicyConfigRefs:
    - group: projectcontour.io
      kind: RatelimitPolicy
      name: generated-name-for-effective-policy
```

One thing to handle here is what the `targetRef` in this generated Policy would be set to, since this shouldn't actually be applied to any resource.

Downsides:
- Have to give RBAC to the Gateway controller to create/update a new resource
- Effective configuration is not in the Route itself, have to go look at another object

---

The above option becomes a little more attractive, if the upstream APIs supply a `PolicyAttachment` type similar to `ReferenceGrant` that connects some implementation specific Policy resource and the Gateway API resource (or other) that it targets.

The generated Status would not reference a Gateway API PolicyAttachment resource but rather the implementation specific Policy.

```go
type PolicyAttachment struct {
  metav1.TypeMeta   `json:",inline"`
  metav1.ObjectMeta `json:"metadata,omitempty"`

  Spec PolicyAttachmentSpec `json:"spec"`

  Status PolicyAttachmentStatus `json:"status"`
}

type PolicyAttachmentSpec struct {
	// TargetRef identifies an API object to apply policy to.
	TargetRef PolicyTargetReference `json:"targetRef"`

  Default LocalObjectReference `json:"default"`

  Override LocalObjectReference `json:"override"`
}
```

An instance of a PolicyAttachment might look like:

```yaml
kind: PolicyAttachment
apiVersion: gateway.networking.k8s.io/v1alpha1
metadata:
  name: ratelimit-policy-attachment
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo
  default:
    group: projectcontour.io
    kind: RatelimitPolicy
    name: default-policy
  override:
    group: projectcontour.io
    kind: RatelimitPolicy
    name: override-policy 
```

This idea has other implications and might be something to explore as it gives some structure to implementers of the API.
