### DISCUSSION TITLE
Including version in `Gateway` as extended conformance

### DISCUSSION THREAD

**Discussion by pmalek** [kubernetes-sigs/gateway-api#1564] [Ideas]
Just wondering what's community's take on adding version to `Gateway` as part of the extended conformance. `version` would designate the version of implementation to be used (i.e. a version of an image).

The idea behind this would be to decrease the reference chain with current possibilities (an object referenced by `GatewayClass`, which in turn is referenced by `Gateway`).

It does make sense for e.g. Kong's implementation, but we'd also like to gauge the support/need for such change from the community?

Would anyone be **strongly** opposed to putting such a thing into extended?

( Another possible field to consider would be the registry/image name to be used. Hypothetically, if that would also get traction then we might consider a different approach than solely with `version` )

**Comment by howardjohn** [comment]
What does it mean to have "version"?

**Reply by pmalek** [reply]
Added that in the post. The idea would be to indicate the version of the implementation to be used (i.e. the container image version)

**Reply by howardjohn** [reply]
Does it need to be programatic? Or would something like this work:

```yaml
  conditions:
  - lastTransitionTime: fake
    message: Gateway accepted by controller version 1.2.3
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: fake
    message: Gateway data plane version 3.4.5 scheduled
    reason: ResourcesAvailable
    status: "True"
    type: Scheduled
```
