### DISCUSSION TITLE
How to support backed service external to the cluster in HTTPRoute

### DISCUSSION THREAD

**Discussion by Amila-Rukshan** [kubernetes-sigs/gateway-api#1573] [Q&A]
Consider following `HTTPRoute` and external `Service` which calls the external backend which is [webhook.site](https://webhook.site) and its base path is `/2457afc0-c3c0-46a0-a389-a85023b8eabe`
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route-webhook
  namespace: abc
spec:
  hostnames:
  - gw.wso2.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: Default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: web-hook-service
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /my-api/7.5.0
      method: GET
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /2457afc0-c3c0-46a0-a389-a85023b8eabe
``` 
```
apiVersion: v1
kind: Service
metadata:
  namespace: abc
  name: web-hook-service
spec:
  type: ExternalName
  externalName: webhook.site
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
```

Base path of the backend is added as a replacePrefixMatch and domain and ports are in the service.

Is this the correct way to achieve it for cluster external services?
