### DISCUSSION TITLE
Ability to replace trailing slash with replacePrefixMatch

### DISCUSSION THREAD

**Discussion by tonygilkerson** [kubernetes-sigs/gateway-api#1981] [Ideas]
I have what I think is a simple use case and I don't see how to do with GatewayAPI.  I am trying to figure out if need to open a bug issue or not.

I want requests to `/api/foo`, `/api/bar` and `/api/etc` to be rewritten as `/foo`, `/bar`, `/etc`

I know I could do it with three rules and I tried that but my app as alot of endpoints and eventually I got an error for too many rules. I feel like I should be able to do it with the yaml below but instead the trailing `/` in `PathPrefix` is dropped and what I end up with is request to `//foo`, `//bar` and `//etc`

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: myroute
spec:
  hostnames:
  - mydomain.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: apps
    namespace: istio-system
  rules:
  - backendRefs:
    - kind: Service
      name: myapi
      port: 8080
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replacePrefixMatch: /
          type: ReplacePrefixMatch
    matches:
    - path:
        type: PathPrefix
        value: /api/

```
