### DISCUSSION TITLE
Standard Gateway names and namespaces, other help for Helm chart writers

### DISCUSSION THREAD

**Discussion by youngnick** [kubernetes-sigs/gateway-api#2133] [Ideas]
Quite a few times when I've been discussing Gateway API with folks, the question of how to make a standard Helm chart that includes a HTTPRoute instead of an Ingress comes up, and I don't have a good answer.

The level of magic in Ingress had the nice property that a Helm chart author could just include an Ingress object, and if there was a default Ingress implementation, everything would _just work_.

It would be nice to approximate something like that in Gateway API.

My proposal here is that we define a conventional default Gateway that will expose HTTPRoutes attached to it to the internet. Then implementations _may_ choose to include that as part of their install, probably with a flag of some sort to be able to disable it.

Additionally, we provide some guidelines for Helm chart writers as to how to include a HTTPRoute (or other Route type) in their charts (basically, it will need a chart value for parent Gateway name and namespace, which will default to the conventional one).

If we do a conventional default Gateway, I would think it should look like this, to mirror Ingress functionality:

```yaml
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: internet # Other options, external, public, or similar.
  namespace: default # The only namespace aside from kube-system that's basically guaranteed to exist
spec:
  gatewayClassName: implementationGWC # Each implementation will need to fill this out
  listeners:  
  - protocol: HTTP
    port: 80
    name: internet-http-gw
    allowedRoutes:
      namespaces:
        from: All
```

If an implementation does not wish to support this Ingress-style ease-of-use Gateway, then it is free to not supply it. But if supplied, it must _at least_:
- have at least one listener that can accept HTTPRoutes (only HTTPS is fine as well as only HTTP as above, but will require additional config and TLS certificate generation)
- Accept routes from all namespaces

This would also allow administrators to have a standard place to customize if they wish, or to delete if they want chart installers to have to take definite action to have their services exposed.

At the very least, if we don't want to do something like this, we should record that, and why not, so that implementations don't all end up doing their own things.
