### DISCUSSION TITLE
Unsupported value: "ResponseHeaderModifier"

### DISCUSSION THREAD

**Discussion by braydenolsen** [kubernetes-sigs/gateway-api#2212] [Q&A] [answered]
Hello,

I have been following this guide: [HTTP header modifier](https://gateway-api.sigs.k8s.io/guides/http-header-modifier/)
Within the guide it talks about the [ResponseHeaderModifier](https://gateway-api.sigs.k8s.io/guides/http-header-modifier/#http-response-header-modifier) but whenever I try to put the ResponseHeaderModifier filter within my HTTPRoute object .yaml file (component-resource-route), it gives me the following error when I use the command `kubectl describe httproute component-resource-route`:

```
Name:         component-resource-route
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1beta1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2023-07-19T14:24:42Z
  Generation:          9
  Resource Version:    791502
  UID:                 7816a0ed-eacc-40f3-982d-4ee89f27b88c
Spec:
  Hostnames:
    localhost
  Parent Refs:
    Group:  gateway.networking.k8s.io
    Kind:   Gateway
    Name:   ias-api-gateway
  Rules:
    Backend Refs:
      Group:
      Kind:    Service
      Name:    component-resource
      Port:    9090
      Weight:  1
    Filters:
      Response Header Modifier:
        Add:
          Name:   Access-Control-Allow-Origin
          Value:  *
          Name:   Access-Control-Allow-Methods
          Value:  *
          Name:   Access-Control-Allow-Headers
          Value:  *
      Type:       ResponseHeaderModifier
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /users
Status:
  Parents:
    Conditions:
      Last Transition Time:  2023-07-21T16:54:46Z
      Message:               All references are resolved
      Observed Generation:   9
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
      Last Transition Time:  2023-07-21T16:54:46Z
      Message:               All rules are invalid: spec.rules[0].filters[0].type: Unsupported value: "ResponseHeaderModifier": supported values: "RequestRedirect", "RequestHeaderModifier"
      Observed Generation:   9
      Reason:                UnsupportedValue
      Status:                False
      Type:                  Accepted
    Controller Name:         k8s-gateway.nginx.org/nginx-gateway-controller
    Parent Ref:
      Group:      gateway.networking.k8s.io
      Kind:       Gateway
      Name:       ias-api-gateway
      Namespace:  default
Events:           <none>
``` 

Here is the HTTPRoute object .yaml file:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: component-resource-route
spec:
  parentRefs:
  - name: ias-api-gateway
  hostnames:
  - "localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /users
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        add:
        - name: Access-Control-Allow-Origin
          value: "*"
        - name: Access-Control-Allow-Methods
          value: "*"
        - name: Access-Control-Allow-Headers
          value: "*"
    backendRefs:
    - name: component-resource
      port: 9090
```

And the Gateway object file:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ias-api-gateway
spec:
  gatewayClassName: nginx
  listeners:  
  - protocol: HTTP
    port: 9080
    name: http
```

Here is the version of Kubernetes I am using:

```
Client Version: v1.27.0
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

And the Minikube version I am using:

```
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

I am also using version 0.5.0 of nginx-kubernetes-gateway as my gateway controller

Finally, I am using v0.7.1 of the gateway api.

I don't understand why it is giving me the `Unsupported value: "ResponseHeaderModifier"` error when I ask it to describe the HTTPRoute, from what I understand wasn't this added in a recent version?

Thanks for the help.
