### DISCUSSION TITLE
Clarification on precedence matching semantics with HTTPRoutes with intersecting hostnames

### DISCUSSION THREAD

**Discussion by arkodg** [kubernetes-sigs/gateway-api#2294] [General]
Lets take this example where two HTTPRoutes are attached to the same gateway
* HTTPRoute `foo-route` serves `foo.example.com` and matches on `/foo`
* HTTPRoute `baz-route` serves `*.example.com` and matches on `/baz`

What happens when the request has `Host: foo.example.com` && `Path: /baz`
* Is the match unsuccessful because it should match `foo-route` / `foo.example.com` hostname but cannot find a path match
OR
* is the match successful because it matches `baz-route` / `*.example.com` and finds a match for the `/baz` path 

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: foo-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "foo.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /foo
    backendRefs:
    - name: foo-svc
      port: 8080
 ---
 apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: baz-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "*.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /baz
    backendRefs:
    - name: baz-svc
      port: 8080     
```      

Here's the relevant part from the HTTPRoute
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRoute
```
In the event that multiple HTTPRoutes specify intersecting hostnames (e.g. overlapping wildcard matching and exact matching hostnames), precedence must be given to rules from the HTTPRoute with the largest number of:

Characters in a matching non-wildcard hostname.
Characters in a matching hostname.
If ties exist across multiple Routes, the matching precedence rules for HTTPRouteMatches takes over.
```

**Comment by rainest** [comment]
This broadens to whether or not inbound request matches can cascade from a more to less specific Listener (where, at present, Hostname is the only match criteria that supports wildcards). Existing language in the spec has:

> The incoming hostname MUST be matched using the Hostname field for each Listener in order of most to least specific. That is, exact matches must be processed before wildcard matches.

but does not have explicit language about attempting to continue match finding on less specific Listeners once all attached routes on a more specific Listener have been exhausted.

If we do not allow cascades, and users wish to match both `foo.example.com/bar` and `bar.example.com/bar` with `foo.example.com` and `*.example.com` Listeners, they would need to create multiple HTTPRoutes with that path, one for each hostname. This requires knowledge of the spec and, if these are effectively the same route (both point to a single upstream service that serves `foo.example.com` and `bar.example.com` equally), could cause issues with session affinity and load balancing.

---

No cascade likely has consequences for Gateway collapsing. If you start with GatewayA, which only has a `foo.example.com` Listener, and GatewayB, which only has a `*.example.com` Listener, collapsing would mask a `bar.example.com/foo` route on the latter without cascade matching. This would likely be difficult to handle since the routes are separate resources, and you can't easily rely on knowing the complete set when deciding whether or not to collapse. If you do try, you could hit a scenario where simply adding a route results in two previously collapsed Gateways separating, which arguably breaks the expected separation of roles (application developers arguably should not be able to make changes that affect cluster operator-managed resources' implementation)

---

Kong's implementation cannot easily handle a no-cascade rule. It builds a list matches from the complete set of all routes across all hostnames, sorts them according to specificity, and walks down the list until it finds a match. A route for `*.example.com/bar` would have lower specificity than a `foo.example.com/bar` route, but the router will match `foo.example.com/bar` to the former if the latter does not exist.

We could probably work around this by creating a `foo.example.com/` prefix match rule with a proxy-served 404 if there is a `foo.example.com` Listener and no such user-specified prefix rule. I don't know if this would have any adverse effects but cannot think of any off the top of my head.

That workaround may not work well if the instance also ingests Ingress resources, though handling both those and Gateway API resources is probably ill-advised "here be dragons" territory where compliance with either spec goes a bit awry anyway.

**Reply by youngnick** [reply]
I don't think that we've ever intended for matches to be able to cascade as you describe - I personally have always assumed that requests must match a single listener, the first listener in the precedence rules we established, _using only Listener properties_.

I think that's the reason this is not well covered in the spec - none of us discussing it before ever really considered it a possibility.

Additionally, when considering Gateway merging (and again this may be poorly captured in the spec), at the time we were discussing this, we all agreed that it was expected that an implementation would read in _all_ the Gateways, evaluate which ones were marked as "to be merged", then effectively take _all_ of those listeners and put them together into a virtual Gateway, _then_ check the Listeners for conflicts using roughly the same rules as for single-Gateway Listeners, and then use the inter-Gateway priority rules (basically, oldest wins) to determine what config wins in the event of a conflict there.

I guess I would sum this up as the mental model I've always had here:

When routing traffic in Gateway API:
- first, choose a distinct Listener. This is the first listener in the total list of listeners, using the listed precedence rules. The most relevant one here is that a more specific hostname beats a less specific hostname, so a wildcard will always come last.
- Then, choose a Route.

This model is a two-stage model, so there is an implied deny at the end of each distinct listener, so that traffic cannot fall through to less specific listeners.

As @howardjohn says, this is how SNI matching works, so I think that we ported those assumptions to plaintext HTTP too.

I'm going to think on this some more, but at the moment, I'm -1 to allowing fall-through, because of how it keeps the TLS and non-TLS models more similar.

**Reply by arkodg** [reply]
@youngnick  trying to get some more clarity here, does this mean it is not possible for 2 HTTPRoutes attached to the same Gateway Listener to have the same list of hostnames in both of them e.g. 
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: foo-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "foo.example.com"
 ---
 apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: another-foo-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "foo.example.com"
  rules:

```

so the only possible allowed ties are specific hostname and wildcard hostname
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: foo-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "foo.example.com"
 ---
 apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: another-wildcard-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "*.example.com"
  rules:

```
