### DISCUSSION TITLE
Custom backend targets

### DISCUSSION THREAD

**Discussion by hermanbanken** [kubernetes-sigs/gateway-api#2414] [Ideas]
We would like to use:

- GCP CloudRun services / Cloud Functions serverless backends
- GCS Storage Buckets

in conjunction to GKE resources in the same Load Balancer.

The documentation (https://gateway-api.sigs.k8s.io/) mentions (emphasis mine):

> Typed Routes and typed backends - The Gateway API supports typed Route resources and also different types of backends. This allows the API to be flexible in supporting various protocols (like HTTP and gRPC) and various backend targets (like Kubernetes Services, storage buckets, or functions).

As far as I can tell this hasn't been implemented, or I just can't find the references to it. Does support exist? How could we contribute such a thing, or would that need to be done by vendors?

**Comment by howardjohn** [comment]
This would need to be done by an implementation (technically it doesn't _have_ to be Google that does it, although you would need to fully re-implement the GKE Implementation which is probably not fun).

cc @robscott for GKE support

**Reply by robscott** [reply]
Unfortunately I can't commit to any timeline here, but this is something we're working to be able to express in GKE. Like John mentioned, implementing support for something like this is ultimately up to implementations, but we may be able to define some common patterns that can be used with Gateway API to reference custom backends.

**Reply by dprotaso** [reply]
Given that we know implementations know how to route to K8s Services we could provide an extension mechanism to allow third parties to resolve backend ref CRDs to K8s Services. This could be used generically by gateway implementations.

eg. For Knative we know a Knative Service will map to a Kubernetes Service of the same name

I don't know what this mechanic/mapping would be exactly - but it would make the ecosystem very pluggable without requiring implementations to add support for everything

(this would be for in-cluster targets)

**Reply by theRealWardo** [reply]
is there any clarity around common patterns here? I suspect the general idea is of the Gateway API is to reference a CRD that the gateway implementation supports. obviously support would be implementation specific but here's my best guess for a cloud function backend reference as an example:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - group: cloud.google.com
      kind: CloudFunction
      name: example-func
```

is this in the right ballpark?
