### DISCUSSION TITLE
Direct policy for DNS configuration at the gateway

### DISCUSSION THREAD

**Discussion by maleck13** [kubernetes-sigs/gateway-api#2541] [Ideas]
Bringing traffic to your gateway is an important part of configuring and setting up your gateway infrastructure. Having a policy that leverages direct policy attachment to target a Gateway and declaratively expresses dns configuration that can be implemented by individual gateway providers or external integrators/policy providers to ensure a choice of implementation and dns providers would be a valuable addition to Gateway API. 

Using a policy API, would allow us not to rely on annotations but instead provide a common API across gateway providers that could be extended on in the future to for e.g support targeting a HTTPRoute or add in `Overrides and Defaults`.

**Use Case**

I want to be able to define a policy that will decide which DNS provider to use and which routing strategy to use for an entire gateway or a specific listener within a gateway so that I can configure and control how traffic will reach my gateway in the same place as I define my gateway. I don't want this policy to be tied to any specific dns provider or gateway provider as there are many dns providers and so I would like to be able to choose an implementation that supports this policy and the dns providers I want to use. 

**Proposal**

Follow up this discussion, if there is agreement on the value, with a `GEP` that goes more into the details, but at a high level the policy API would look something like:
```
apiVersion: gateway.networking.k8s.io/v1alpha1
kind: DNSPolicy
metadata:
  name: prod
  namespace: gateways
spec:
  providerRef:
    name: route53-credentials
    namespace: gateways
    kind: Secret
  targetRef:
    name: prod-external
    group: gateway.networking.k8s.io
    kind: Gateway
    sectionName someListener # if a different policy was needed for a given listener
  routingStrategy: simple # default initial strategy, there maybe others, in Kuadrant we also have LoadBalanced for multi-cluster
  controllerName: some.group.io/dnsController #used to decide which controller should apply the policy
```

- Policy would be allowed to target a gateway
- A default routingStrategy would be set to simple (other strategies may evolve over time)
- The outcome of this policy targeting a gateway would be an A or CNAME record setup for the listener hosts 
- The providerRef secret would configure which zone id and which provider it was for

**Additional Reading**

We have an existing alpha policy in the kuadrant project that does some of this, it provides more advanced multi-cluster options but here is some more details on the `simple` strategy within a single cluster:

https://github.com/Kuadrant/architecture/blob/main/rfcs/0005-single-cluster-dnspolicy.md

**Multi-Cluster**

DNS based load balancing for distributed gateway instances (for Geo or Resilience) is a use case we are also interested in, but wanted to try solve what is likely the most common use case with this initial GEP. In the document linked above, you will see there is also a load balanced strategy, so the hope is that we can extend the strategy options over time.
