### DISCUSSION TITLE
Combine two (different) matcher (types) with URLRewrite Filter?

### DISCUSSION THREAD

**Discussion by SantoDE** [kubernetes-sigs/gateway-api#2607] [General]
Hey folks,

maybe I'm misunderstanding something but I don't exactly understand why the validation forbids an `HTTPRoute` like that:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: api-example-com-route
  namespace: default
  labels:
    app: apis
spec:
  parentRefs:
    - name: http
      namespace: gloo-system
  hostnames:
    - "api.example.com"
  rules:
    - matches:  
      - path:
          type: PathPrefix
          value: /httpbin/
      - headers:
        - name: version
          value: v2
          type: Exact
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: httpbin
          namespace: httpbin
          port: 8000
```

I totally get that there needs to be _ONE_ path matcher so that the rewrite can take place after. Currently, validation forbids a second matcher (in that case header) [validation logic](https://github.com/kubernetes-sigs/gateway-api/blob/52c2994ed9de1c287a37465490b91cfcf01bf16e/apis/v1/httproute_types.go#L130). Can someone help me understand why? I feel like re-writing a path in cases where a specific header applies is a valid use-case and its not directly interfering with pathes. Why did we initially forbid that?
