### DISCUSSION TITLE
Add support for custom filters and matchers in TCP/UDPRoute

### DISCUSSION THREAD

**Discussion by aryan9600** [kubernetes-sigs/gateway-api#2612] [Ideas]
### Problem
At the moment, the `TCPRoute` and `UDPRoute` APIs are very simple, with the API allowing for only a list of backends to be specified that will receive incoming traffic. In contrast, `HTTPRoute` offers a plethora of ways to match and modify incoming/outgoing traffic. This is obvious, since HTTP is a L7 protocol and thus has much more data to work with. Since TCP and UDP are L4 protocols, there aren't any obvious ways to provide standardized traffic matchers and filters.

### Proposal
But `HTTPRoute` also allows for custom filters and matchers through the `.extensionRef` field which points to another object that contains more details about the required operations. We could add the same capability to `TCPRoute` and `UDPRoute`. This would allow for implementations to offer their own TCP and UDP traffic extensions, which could then be referred to in a `TCPRoute`/`UDPRoute` object.
For example, consider we want to build a custom SSH load balancer. Adding such an extension capability, will then allow redirecting a particular user to a particular backend based on their SSH username. Such behavior is not possible to implement through the existing APIs. Here's a basic example of what this would look like:

```yaml
apiVersion: ssh.networking.io/v1alpha1
kind: SSHMatch
metadata:
  name: admin-match
spec:
  username: admin
---
apiVersion: ssh.networking.io/v1alpha1
kind: SSHMatch
metadata:
  name: guest-match
spec:
  username: guest
```

```yaml
apiVersion: gateway.networking.io/v1alpha2
kind: TCPRoute
metadata:
  name: ssh-route
spec:
  parentRefs:
  - name: metal-lb
  rules:
   - match:
      - type: ExtensionRef
        extensionRef:
            apiVersion: ssh.networking.io/v1alpha1
            kind: SSHMatch
            name: username-match
     backendRefs:
      - name: admin-ssh-svc
        port: 22
   - match:
      - type: ExtensionRef
        extensionRef:
            apiVersion: ssh.networking.io/v1alpha1
            kind: SSHMatch
            name: guest-match
     backendRefs:
      - name: guest-ssh-svc
        port: 22
```

Since extensions are completely optional, the `extensionRef` field can be introduced without any friction while enabling implementations to have custom behavior like above.
