### DISCUSSION TITLE
Create a HTTPRoute to a service in the same namespace

### DISCUSSION THREAD

**Discussion by Roemer** [kubernetes-sigs/gateway-api#2774] [Q&A] [answered]
I got a simple service like:
```yaml
apiVersion: v1
  kind: Service
  metadata:
    name: build-service
    namespace: appl-lab-e1
  spec:
    ports:
    - name: proxy-port
      port: 8082
      protocol: TCP
      targetPort: proxy-port
```
and now I want a HTTPRoute to redirect all traffic for an url to that service.
I am trying with something like:
```yaml
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: hello
spec:
  parentRefs:
    - name: <???>
      namespace: <same as the service>
  hostnames:
    - "my-route.domain.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: build-service
          port: 8082
```
and I tried around with various values for the `parentRefs` but I was never able to get any requests in my service when connecting to the defined hostname. Can anyone enlighten me and tell me, what I am doing wrong?
Many thanks
