### DISCUSSION TITLE
How to achieve single hostname with BOTH https and http path

### DISCUSSION THREAD

**Discussion by e33ivanyauwai** [kubernetes-sigs/gateway-api#2929] [General]
How to achieve single hostname with BOTH https and http path, e.g.:
"/" with https tcp443
"/plaintext" with http tcp80

Something like:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
spec:
  parentRefs:
  - name: gateway-all
    namespace: default
    sectionName: http
  hostnames:
  - "www.example.com"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-only
spec:
  parentRefs:
  - name: gateway-all
    namespace: default
    sectionName: https
  hostnames:
    - "www.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /plaintext
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: http
            port: 80
```
