### DISCUSSION TITLE
Extending GatewayAPI + ClientSettingsPolicy

### DISCUSSION THREAD

**Discussion by Coder63** [kubernetes-sigs/gateway-api#3228] [Q&A]
I'm running Gateway API v1.1.0 & Nginx Gateway Fabric v1.3.0.  I'm following this example- https://docs.nginx.com/nginx-gateway-fabric/how-to/traffic-management/client-settings/  to test it out.  

Gateway.yaml & Client Setting Policy.yaml 

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: gke-l7-rilb
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.example.com"
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: gateway-client-settings
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
  body:
    maxSize: "10" # sizes without a unit are bytes.

```

I don't see any status /Accepted  for the clientsettingspolicies.gateway.nginx.org. Started this thread  https://github.com/nginxinc/nginx-gateway-fabric/discussions/2306 and got NGF implementation using `GatewayClass: Nginx`.  Can we implement it without this nginx GatewayClass native to gateway.networking.k8s.io CRD's  ?
