### DISCUSSION TITLE
Route to different Service based on header with same path

### DISCUSSION THREAD

**Discussion by pramodbabua** [kubernetes-sigs/gateway-api#3331] [General]
Using the HTTPRoute resource, I wanted to achieve the below, 

/api with header service=service1 should route to backend service 1
/api with header service=service2 should route to backed service 2

I was able to achieve it by writing HTTPRoute as below,

```
 rules:
 - matches:
   - path:
       type: PathPrefix
       value: /api
     headers:
      - type: Exact
        name: service
        value: echo
   backendRefs:
      - name: echo
        kind: Service
        port: 1027 
 - matches:
   - path:
       type: PathPrefix
       value: /api
     headers:
      - type: Exact
        name: service
        value: httpbin
   backendRefs:
      - name: httpbin
        kind: Service
        port: 80
```

Is there a cleaner way to achieve this rather than rewriting the pathprefix for every match? Potentially looking at overriding root path to say '/api' instead of '/' for this httproute resource as a whole.
