### ISSUE TITLE
docs: improve explanation of secure usage of AllowedRoutes selectors

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1033]
**What would you like to be added**:
Add additional content (perhaps in the [Security Model](https://gateway-api.sigs.k8s.io/concepts/security-model/) section?) to better describe how [`AllowedRoutes`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.AllowedRoutes) should be configured for secure operation, likely linking out to https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors for additional context on how to use selectors.

**Why this is needed**:
It's quite easy to configure a permissive policy with `FromNamespaces: All`, but there's not much information on how `FromNamespaces: Selector` can be used to narrow the allowed scope from where Routes may bind, or potential risks of specifying a selector like `Label` without restrictive RBAC instead of explicitly selecting a namespace by `metadata.Name`.

As an example provided by @robscott 
> I think many users may end up with something like this:
```
namespaces:
  from: Selector
  selector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - foo
      - bar
```
