### ISSUE TITLE
apply httproute.yaml err info： error validating data: ValidationError(HTTPRoute.spec.rules[0].filters[0].requestRedirect): unknown field "path" in io.k8s.networking.gateway.v1alpha2.HTTPRoute.spec.rules.filters.requestRedirect; if you choose to ignore these errors, turn validation off with --validate=false

### ISSUE THREAD

**Issue by eoshardwork** [kubernetes-sigs/gateway-api#1076]
**What happened**:
apply httproute error
**What you expected to happen**:
apply httproute can be success
**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f ../kubernetes/httproute.yaml
error: error validating "../kubernetes/httproute.yaml": error validating data: ValidationError(HTTPRoute.spec.rules[0].filters[0].requestRedirect): unknown field "path" in io.k8s.networking.gateway.v1alpha2.HTTPRoute.spec.rules.filters.requestRedirect; if you choose to ignore these errors, turn validation off with --validate=false
```

httproute.yaml
```
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: user-dev
  namespace: default

spec:
  parentRefs:
    - name: traefik-gateway

  hostnames:
    - example.com

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /from
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplacePrefixMatch
              substitution: /from
      backendRefs:
        - name: user-dev
          port: 80
          weight: 1

```

**Anything else we need to know?**:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
