### ISSUE TITLE
Confusing of HTTPPathModifier 

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-sigs/gateway-api#1165]
https://github.com/kubernetes-sigs/gateway-api/blob/c7da26bec21093f2eec792dd49386c344982ea9e/apis/v1alpha2/httproute_types.go#L719-L733

How could i rewrite url like  `/foo/bar` prefixed with foo to `/bar` , it does not allow setting match value

**Comment by robscott** [comment]
Thanks for the question @hzxuzhonghu! I think #1124 and #1162 will help make this a bit clearer. The value that is being replaced is from the path match. So if you want to use a prefix match to rewrite requests starting with `/foo/bar` to `/bar`, you could use config like this:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-filter-rewrite
spec:
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /foo/bar
      filters:
      - type: URLRewrite
         urlRewrite:
           path:
             type: ReplacePathPrefix
             replacePathPrefix: /bar
      backendRefs:
      - name: example-svc
        weight: 1
        port: 80
```
