### ISSUE TITLE
Services to Endpoints don't work

### ISSUE THREAD

**Issue by mbinette** [kubernetes-sigs/gateway-api#1222]
I have setup a Gateway using gatewayClassname of gke-l7-gxlb. I have setup HTTPRoutes to backend services that all work fine as long as the backendRefs Service is going to a Pod. But when the Service goes to an Endpoint, it fails.

**What happened**
When you go to the configured URL you get a 502 error. It never hits the backend Endpoint.

**How to reproduce/description**
If the backendRefs Service is setup to go to an Endpoint then everything is accepted when you do the `kubectl apply`; no errors or warning are logged, and the Google Console shows it as Healthy but with 0 of 0 instances. When you try to hit the configured URL you get a 502 error from the load balancer. I've attached the full set of YAML entries if you need to see the Gateway, HTTPRoute, BackendConfig, Service, and Endpoint definitions in their entirety.

The Endpoint is an IP address of a Google VM instance in the same VPC and subnet as my k8s project.

The Service and Endpoint (only thing different from the ones that work) looks like this:
```
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-dev
  namespace: "wordpress"
  annotations:
    cloud.google.com/backend-config: '{"default": "gke-backendconfig-wordpress"}'
spec:
  ports:
  - name: dev-http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wordpress-dev
  namespace: "wordpress"
subsets:
  - addresses:
      - ip: 10.1.0.8
    ports:
    - name: dev-http
      protocol: TCP
      port: 80
```

**Anything else we need to know?**:

The `kubectl describe` for the service has a proper Endpoint in the same VPC:
```
Name:              wordpress-dev
Namespace:         wordpress
Labels:            <none>
Annotations:       cloud.google.com/backend-config: {"default": "gke-backendconfig-wordpress"}
                   cloud.google.com/neg: {"exposed_ports":{"80":{}}}
                   cloud.google.com/neg-status:
                     {"network_endpoint_groups":{"80":"k8s1-13053f64-wordpress-wordpress-dev-80-2eb51c91"},"zones":["us-central1-b"]}
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.80.5.105
IPs:               10.80.5.105
Port:              dev-http  80/TCP
TargetPort:        80/TCP
Endpoints:         10.1.0.8:80
Session Affinity:  None
Events:
  Type    Reason  Age                 From                   Message
  ----    ------  ----                ----                   -------
  Normal  SYNC    56m (x10 over 84m)  sc-gateway-controller  SYNC on wordpress/wordpress-dev was a success
  Normal  ADD     56m                 sc-gateway-controller  wordpress/wordpress-dev
  Normal  SYNC    36m (x8 over 56m)   sc-gateway-controller  SYNC on wordpress/wordpress-dev was a success
  Normal  ADD     36m                 sc-gateway-controller  wordpress/wordpress-dev
  Normal  SYNC    97s (x13 over 36m)  sc-gateway-controller  SYNC on wordpress/wordpress-dev was a success
```
The primary difference here is the 10.1.0.8 Endpoint is in the same VPC as everything else but the Pods secondary subnet is different. I obviously can't assign my VM an address in k8s managed subnet.

[gateway.txt](https://github.com/kubernetes-sigs/gateway-api/files/8952406/gateway.txt)
