### ISSUE TITLE
ManagedCertificate not found using `networking.gke.io/pre-shared-certs` option

### ISSUE THREAD

**Issue by masus04** [kubernetes-sigs/gateway-api#1275]
**What happened**:
According to the [Deploying Gateways](https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways#tls_between_client_and_gateway) post, I've been trying to deploy a Gateway to a GKE cluster using an existing `ManagedCertificate`.

I have used the `ManagedCertificate` with an `Ingress` before, so I assume it is configured correctly.

I then tried to reference it in the Gateway as follows:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: gke-l7-gxlb
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: {{ .Values.certificates.managedCertName | quote }}
  addresses:
  - type: NamedAddress
    value: {{ .Values.gateway.staticIPName }}
```

which results in the Gateway logging the following event/error:
```yaml
Warning  SYNC    24s (x5 over 8m26s)  sc-gateway-controller  failed to translate Gateway "default/{{managedCertName}}": Error GWCER105: Listener "https" is invalid, err: SslCertificate "global/sslCertificates/{{managedCertName}}" does not exist.                                                                                                                                                                          
```

**What you expected to happen**:
I expected the Gateway to find and unse the credentials provided under the **tls** key.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a `ManagedCertificate` and reference it using a `Gateway`

**Anything else we need to know?**:
I also can't remove the `Gateway` as soon as it's deployed, but that might be a separate issue.
