### ISSUE TITLE
Add support for manipulating response headers in the `HTTPRouteFilter` API

### ISSUE THREAD

**Issue by aryan9600** [kubernetes-sigs/gateway-api#1323]
**What would you like to be added**:

It'd be great if `HTTPRouteFilter` had a field to manipulate response headers being sent from  a backend (or a group of backends) similar to `RequestHeaderModifier`.

This can be done by adding a new field `ResponseHeaderModifier` of type `HTTPResponseHeaderFilter` which would have the same API as the existing `HTTPRequestHeaderFilter`. Alternatively, `HTTPRequestHeaderFilter` could be renamed to `HTTPHeaderFilter` and both `RequestHeaderModifier` and `ResponseHeaderModifier` would be of type `HTTPHeaderFilter`.

Similar specifications can be seen in service meshes like Istio's `VirtualService` (ref: https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers) and ingresses like Contour's `HTTProxy` (ref: https://projectcontour.io/docs/v1.22.0/config/api/#projectcontour.io/v1.Route)

**Why this is needed**:

Just like editing request headers can be useful, the same goes for response headers. For example, it allows teams to add/remove cookies for only a certain backend, which can help in identifying certain users that were redirected to that backend previously.

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-response-header
spec:
  hostnames:
    - response.header.example
  rules:
    - filters:
      - type: ResponseHeaderModifier
        responseHeaderModifier:
          set:
            name: Set-Cookie
            value: user=insider
      backendRefs:
      - name: example-svc
        weight: 1
        port: 80
```

Another potential use case could be when you have a frontend that needs to know whether it's talking to a stable or a beta version of the backend server, in order to render different UI or adapt its response parsing accordingly.

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-response-header
spec:
  hostnames:
    - response.header.example
  rules:
    - backendRefs:
      - name: example-svc-beta
        weight: 50
        port: 80
        filters:
           - type: ResponseHeaderModifier
             responseHeaderModifier:
              set:
                name: build
                value: beta
      - name: example-svc-stable
        weight: 50
        port: 80
```

If this requires a GEP, I'd be happy to start working on one.
