### ISSUE TITLE
Support HTTPRoute filters for external load balancing

### ISSUE THREAD

**Issue by karmux** [kubernetes-sigs/gateway-api#1341]
**What would you like to be added**:
I would like to have following setup with external load balancer and HTTPRoute:
`/s/service1/foo/bar` requests being sent to `service1` Service with path `/foo/bar`.

Currenctly it sends full path `/s/service1/foo/bar` to `service1` Service.
Moreover it is not documented anywhere that external load balancers do not support HTTPRoute filters.

I see this log when I describe my httproute:
```
Warning  SYNC    4m27s (x8 over 33m)  sc-gateway-controller  RouteRejected: Bind of HTTPRoute "default/services-router" to Gateway "default/external-http" failed: Error GWCER104: HTTPRoute "default/services-router" is misconfigured, err: rule filters are not supported for external load balancing.
```

Example httproute yml file:
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: services-router
spec:
  parentRefs:
  - kind: Gateway
    name: external-http
  rules:
  - filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: ""
  - matches:
    - path:
        value: /s/service1/
    backendRefs:
    - name: service1
      port: 80
  - matches:
    - path:
        value: /s/service2/
    backendRefs:
    - name: service2
      port: 80
```

**Why this is needed**:
This is basic functionality of proxy or load balancing and would make it very easy to expose backend services to the public via paths.
