### ISSUE TITLE
Clarify whether an http redirect is conditional or unconditional

### ISSUE THREAD

**Issue by pleshakov** [kubernetes-sigs/gateway-api#1371]
**What would you like to be added**:

In the redirect examples here https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#redirects the backendRefs are always configured. Like below:
```yaml
. . .
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
      backendRefs:
      - name: example-svc
        weight: 1
        port: 80
```

If the redirect is unconditional (always fires), then the backendRefs are unnecessary, because the proxy will never proxy to the backends.

However, if the redirect is conditional, then the backendRefs are OK. However, I think it make sense to clarify in the examples when the redirect will not fire and why the backendRefs are needed. Also, I think it makes sense to clarify that in the docs https://github.com/kubernetes-sigs/gateway-api/blob/a7a465ababc8b7c2cd9eaa1ab769496704fee92a/apis/v1beta1/httproute_types.go#L819 

**Why this is needed**:
- to ensure consistent behavior across implementations
- to make the documentation clearer. 

See also:
- loop protection proposal -- https://github.com/kubernetes-sigs/gateway-api/issues/1185
- a related discussion about redirect behavior -- https://github.com/kubernetes-sigs/gateway-api/discussions/1360
