### ISSUE TITLE
TCPRouteRule and BackendRef 

### ISSUE THREAD

**Issue by ivanmatmati** [kubernetes-sigs/gateway-api#1378]
**What happened**:
Implementing a GW Api implementation, we're focusing on TCPRoute. I'm puzzled by the structures used in v1alpha2 for TCPRoute.
I see that TCPRouteSpec contains a slice of TCPRouteRule like this: `Rules []TCPRouteRule`. But a TCPRouteRule itself is simply a slice of BackendRef like this: `BackendRefs []BackendRef`. Comments in code don't reveal the reason for this structure. Finally, through Rules and BackendRefs, we're manipulating a slice of slice of BackendRef but for apparent reason.
**What you expected to happen**:
As there's no obvious reason for using of slice of slice of BackendRef, why not simply a slice of BackendRef ? This structure implies the two following examples should be different.But how?
```
rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: my-foo-service
          port: 6000
          weight: 1
        - group: ''
          kind: Service
          name: my-foo-service
          port: 8000
          weight: 1
```
and
```
rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: my-foo-service
          port: 6000
          weight: 1
    - backendRefs :
        - group: ''
          kind: Service
          name: my-foo-service
          port: 8000
          weight: 1
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
