### ISSUE TITLE
Clarify Route matching precedence language

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/gateway-api#1381]
The language describing Route match precedence order still seems a little unclear: https://github.com/kubernetes-sigs/gateway-api/blob/c1adb20f2d476dee1b95c255aedfa9b49e8b59f0/apis/v1beta1/httproute_types.go#L144-L167

In https://github.com/kubernetes-sigs/gateway-api/issues/1370 I interpreted the section about `largest number of...Header matches` to mean the Rule with the largest number of matching headers in a `HTTPRouteMatch` whereas another valid interpretation is below:

@sunjayBhatia reading the current spec literally, I would think this request should go to `infra-backend-v1`. Per https://github.com/kubernetes-sigs/gateway-api/blob/a3f769e5c690546140b6b9f0db5aea4d766b8f68/apis/v1beta1/httproute_types.go#L143-L152, we should prioritize the **Rule** with the greatest number of header matches, which in this case is:

```
 # Matches "color: blue" OR "color: green"
  - matches:
    - headers:
      - name: color
        value: blue
    - headers:
      - name: color
        value: green
    backendRefs:
    - name: infra-backend-v1
      port: 8080
```

Since this is a single Rule that has 2 header matches (even though each individual Match within the Rule only has one each).

_Originally posted by @skriss in https://github.com/kubernetes-sigs/gateway-api/issues/1370#issuecomment-1238472815_

We should clarify this language a bit and make a decision on what is the conformant behavior, to change or keep https://github.com/kubernetes-sigs/gateway-api/issues/1370
