### ISSUE TITLE
Conformance test httproute-matching-across-routes generates unexpected HTTPRoute Paths.

### ISSUE THREAD

**Issue by rperper** [kubernetes-sigs/gateway-api#1444]
**What happened**:
When running a conformance test with our company's Kubernetes Gateway Load Balancer (LiteSpeed Technologies), the httproute-matching-across-routes conformance test failed using today's (07 Oct 2022 main branch) conformance test code  When checking the .yaml, it shows:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: matching-part1
  namespace: gateway-conformance-infra
spec:
  parentRefs:
  - name: same-namespace
  hostnames:
  - example.com
  - example.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    - headers:
      - name: version
        value: one
    backendRefs:
    - name: infra-backend-v1
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: matching-part2
  namespace: gateway-conformance-infra
spec:
  hostnames:
  - example.com
  parentRefs:
  - name: same-namespace
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v2
    - headers:
      - name: version
        value: two
    backendRefs:
    - name: infra-backend-v2
      port: 8080
```
Which would mean that for `matching-part2` there would only be a single path `/v2`.  However when doing a `kubectl describe httproute -A` I see for that route:
```
Name:         matching-part2
Namespace:    gateway-conformance-infra
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1beta1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2022-10-07T19:22:19Z
  Generation:          1
  Managed Fields:
    API Version:  gateway.networking.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:hostnames:
        f:parentRefs:
        f:rules:
    Manager:      conformance.test
    Operation:    Update
    Time:         2022-10-07T19:22:19Z
    API Version:  gateway.networking.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:parents:
    Manager:         ls-k8s-webadc
    Operation:       Update
    Subresource:     status
    Time:            2022-10-07T19:22:19Z
  Resource Version:  6118634
  UID:               ebbcad38-9af9-4345-bb10-32e0cae62af6
Spec:
  Hostnames:
    example.com
  Parent Refs:
    Group:  gateway.networking.k8s.io
    Kind:   Gateway
    Name:   same-namespace
  Rules:
    Backend Refs:
      Group:   
      Kind:    Service
      Name:    infra-backend-v2
      Port:    8080
      Weight:  1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /v2
      Headers:
        Name:   version
        Type:   Exact
        Value:  two
      Path:
        Type:   PathPrefix
        Value:  /
Status:
  Parents:
    Conditions:
      Last Transition Time:  2022-10-07T19:22:19Z
      Message:               
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
    Controller Name:         litespeedtech.com/lslbd
    Parent Ref:
      Group:  gateway.networking.k8s.io
      Kind:   Gateway
      Name:   same-namespace
Events:       <none>
```

**What you expected to happen**:
I did not expect to see the root path `/`; the only path should be `/v2`

**How to reproduce it (as minimally and precisely as possible)**:
Run a conformance test and do a `kubectl get httproute -A` during the test.

**Anything else we need to know?**:
As you'd expect, this results in the test's failure:
```
    --- FAIL: TestConformance/HTTPRouteMatchingAcrossRoutes (1.39s)
        --- PASS: TestConformance/HTTPRouteMatchingAcrossRoutes/3_request_to_'example.com/example'_with_headers_should_go_to_infra-backend-v1 (0.08s)
        --- PASS: TestConformance/HTTPRouteMatchingAcrossRoutes/4_request_to_'example.com/v2'_should_go_to_infra-backend-v2 (1.07s)
        --- FAIL: TestConformance/HTTPRouteMatchingAcrossRoutes/0_request_to_'example.com/'_should_go_to_infra-backend-v1 (30.00s)
        --- PASS: TestConformance/HTTPRouteMatchingAcrossRoutes/6_request_to_'example.com/v2/example'_should_go_to_infra-backend-v2 (0.05s)
        --- FAIL: TestConformance/HTTPRouteMatchingAcrossRoutes/2_request_to_'example.net/example'_should_go_to_infra-backend-v1 (30.00s)
        --- FAIL: TestConformance/HTTPRouteMatchingAcrossRoutes/1_request_to_'example.com/example'_should_go_to_infra-backend-v1 (30.00s)
        --- FAIL: TestConformance/HTTPRouteMatchingAcrossRoutes/7_request_to_'example.com/'_with_headers_should_go_to_infra-backend-v2 (30.00s)
        --- FAIL: TestConformance/HTTPRouteMatchingAcrossRoutes/5_request_to_'example.net/v2'_should_go_to_infra-backend-v1 (30.00s)
```
Failing because all routes get an added trailing root `/` path.

Just to be sure I wasn't creating the problem inadvertently, I put in a trace statement, tracing the httproute at the time it was detected:
```
I1007 20:41:43.526163       1 gw.go:501] HTTPRoute JUST ADDED: &{{ } {matching-part2  gateway-conformance-infra  75650db3-271d-4a25-a019-8ef2dddbe3ae 6140420 1 2022-10-07 20:41:43 +0000 UTC <nil> <nil> map[] map[] [] []  [{conformance.test Update gateway.networking.k8s.io/v1beta1 2022-10-07 20:41:43 +0000 UTC FieldsV1 {"f:spec":{".":{},"f:hostnames":{},"f:parentRefs":{},"f:rules":{}}} }]} {{[{0xc000a67390 0xc000a673a0 <nil> same-namespace <nil> <nil>}]} [example.com] [{[{0xc000a673d0 [] [] <nil>} {0xc000a67410 [{0xc000a67400 version two}] [] <nil>}] [] [{{{0xc000a673b0 0xc000a673c0 infra-backend-v2 <nil> 0xc000ab92e0} 0xc000ab92e8} []}]}]} {{[]}}}
```
Note there are TWO HttpRouteMatch statements, the first with no headers and the second with the header version=two.
Thanks!

**Comment by robscott** [comment]
Hey @rperper, I think the confusion here is coming from the [default "/" prefix path match](https://github.com/kubernetes-sigs/gateway-api/blob/f533a1e7637a057fd4dc20c9adbc27f8dbd8bc5d/apis/v1beta1/httproute_types.go#L116) we apply for HTTPRoutes. I'm not sure that should matter here though because a "/v2" match should have precedence over "/". Maybe some more details on what you'd expect to happen here would be useful.

**Comment by rperper** [comment]
Hi @robscott !  Indeed a /v2 match will take precedence over '/'.  However, this causes '/' to match at all.  '/' should go to the other backend.  This causes the load balancer confusion: now both backends are eligible for '/' traffic which is why the test fails.  Kubernetes shouldn't be adding rule matches, only using the ones specified and '/' is not specified.

**Comment by rperper** [comment]
Unless the '/' added is intended behavior.  If so, I'll deal with it, just need to know.

**Comment by robscott** [comment]
Hey @rperper! Thanks for checking. The default "/" prefix match is intentional. The idea is that rules match all requests unless specific matches or hostnames are specified, this just makes that behavior a little bit clearer. 

>now both backends are eligible for '/' traffic which is why the test fails.

```
    Matches:
    - Path:
        Type:   PathPrefix
        Value:  /v2
    - Headers:
        Name:   version
        Type:   Exact
        Value:  two
      Path:
        Type:   PathPrefix
        Value:  /
```

To clarify, the first match should only match requests that start with `/v2` and the second match should only match requests that include a `version` header set to `two`. The `/` prefix match that's part of the second match definition does not really have any effect here since it's ANDed with the header match.

I think some of the confusion may be coming from the less than ideal way that kubectl describe renders this resource (we sadly don't have control over that). It may be more helpful to use `kubectl get httproute -oyaml` until kubectl describe works better.
