### ISSUE TITLE
Alternative to get same capability of extensionRef from route match block after discontinuing support for it

### ISSUE THREAD

**Issue by Amila-Rukshan** [kubernetes-sigs/gateway-api#1468]
**What would you like to be added**:
With the following GEP, the extension points within Route match block are going to be removed. 
https://gateway-api.sigs.k8s.io/geps/gep-820/

If I had the some policy defined and targeted at HTTPRoute resource then it will apply for all the route rules. but previously it was possible to apply for a single rule (that granularity is lost after dropping the extensionRef support from filters).

I would like to suggest a way as below. If we modify the [target-ref-api](https://gateway-api.sigs.k8s.io/geps/gep-713/?h=targetref#policy-targetref-api) to support custom properties listed under another property with the value of kind property.
```
kind: SomePolicy
metadata:
  name: ...
spec:
  default:
    type: <type>
    <type>:
      ...              # policy specific properties          
      ...
targetRef:             
    kind: HTTPRoute  
    name: resource-name
    hTTPRoute:
        ruleNames: 
           - my-rule-name-1
```
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: httpbin
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "www.example.com"
  rules:
    - name: my-rule-name-1
      backendRefs:
        - group: ""
          kind: Service
          name: httpbin-1
          port: 80
          weight: 1
       matches:
        - path:
            type: PathPrefix
            value: /
    - name: my-rule-name-2
       backendRefs:
        - group: ""
          kind: Service
          name: httpbin-2
          port: 80
          weight: 1
       matches:
        - path:
            type: PathPrefix
            value: /
  
```

Now the policy is applied to the rule of the HTTPRoute and not all the rules.

**Why this is needed**:

This will help not to split related http routes (going to the same backend and same filters are applied) into a set of HTTPRoute resources by targeting the policy to the HTTPRouteRule.
