### ISSUE TITLE
HTTPRouteResponseHeaderModifier test seems incorrect

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1473]
**What happened**:

I tried to run the latest conformance tests

**What you expected to happen**:

It failed, but I don't think it should have.

**How to reproduce it (as minimally and precisely as possible)**:

You can run the tests with https://github.com/istio/istio/pull/41353 I suppose

**Anything else we need to know?**:

Aside from trivial issue in https://github.com/kubernetes-sigs/gateway-api/pull/1472, the assertions seem generally wrong?

For example:

```yaml
  - matches:
    - path:
        type: PathPrefix
        value: /set
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: X-Header-Set
          value: set-overwrites-values
```

```go
{
  Request: http.Request{
    Path: "/set",
    Headers: map[string]string{
      "Some-Other-Header": "val",
      "X-Header-Set":      "some-other-value",
    },
  },
  Headers: map[string]string{
    "Some-Other-Header": "val",
    "X-Header-Set":      "set-overwrites-values",
  },
  Backend:   "infra-backend-v1",
  Namespace: ns,
}
```

` "Some-Other-Header": "val",` is asserted to be a response header, but it shouldn't be. The test seems to conflate request headers and response headers
