### ISSUE TITLE
webhook: validate HTTPRoute parentRefs

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1481]
**What would you like to be added**:

The `ParentRefs` field in the `CommonRouteSpec` states:
 https://github.com/kubernetes-sigs/gateway-api/blob/21bba43681b3db3a62d7ca9f108bf3be4c0cea71/apis/v1beta1/shared_types.go#L130-L132
For his reason, the `HTTPRoute` webhook should be improved in a way the above condition is always verified. Hence, the following check should be added to the webhook:

if an `HTTPRoute` references more than once the same Gateway as the parent, the `Parentref`'s `SectionName`s must be set and different, otherwise, the validation returns an error.

**Why this is needed**:

This is needed to ensure that an `HTTPRoute` does not reference the same Gateway (or the same listener) more than once.

**Comment by robscott** [comment]
Agree this would be good. One tiny nit - we should validate that SectionName _or_ Port are set to avoid this problem.

**Comment by gyohuangxin** [comment]
I'd like to take this. Can I confirm the requirement is that if there are more than one `ParentRefs` in `HTTPRoute` they must have different `SectionName` or `Port`?
/assign

**Comment by robscott** [comment]
Hey @gyohuangxin, thanks for volunteering! I think we want the following:

If ParentRefs includes 2 or more references to the same parent (based on kind, name, and namespace), those ParentRefs must specify unique SectionName or Port values.

**Invalid:**
```yaml
parentRefs:
- name: foo
   kind: Gateway
-  name: bar
   kind: Gateway
```

**Valid:**
```yaml
parentRefs:
- name: foo
   kind: Gateway
   sectionName: "http"
-  name: bar
   kind: Gateway
   sectionName: "https"
```

I _think_ it would also make sense to require that parentRefs to the same parent don't mix and match sectionName and port. Specifying both on both parentRefs would be valid, but the following would not:

```yaml
parentRefs:
- name: foo
   kind: Gateway
   sectionName: "http"
-  name: bar
   kind: Gateway
   port: 80
```

**Comment by gyohuangxin** [comment]
@robscott Thanks for clarifying this, does it make sense like following:
```
parentRefs:
- name: foo
   kind: Gateway
   sectionName: "http"
   port: 80
-  name: bar
   kind: Gateway
   sectionName: "http"
   port: 81
```

or 

```
parentRefs:
- name: foo
   kind: Gateway
   sectionName: "http"
   port: 80
-  name: bar
   kind: Gateway
   sectionName: "https"
   port: 80
```

**Comment by robscott** [comment]
Hey @gyohuangxin, good question. `sectionName` should always be unique within a resource, so your first example would be invalid. On the other hand, it's possible for two different listeners to be listening on the same port, so your second example would be valid.

**Comment by gyohuangxin** [comment]
@robscott Understand, thanks.

**Comment by mlavacca** [comment]
> If ParentRefs includes 2 or more references to the same parent (based on kind, name, and namespace), those ParentRefs must specify unique SectionName or Port values.
> 
> **Invalid:**
> 
> ```yaml
> parentRefs:
> - name: foo
>    kind: Gateway
> -  name: bar
>    kind: Gateway
> ```

I think this should be valid because the referenced parents are different (foo vs bar). Instead, the following should be considered invalid:

```yaml
parentRefs:
- name: foo
  kind: Gateway
- name: foo
  kind: Gateway
```

For the same reason,
```yaml
parentRefs:
- name: foo
   kind: Gateway
   sectionName: "http"
-  name: bar
   kind: Gateway
   port: 80
```
is valid, while 
```yaml
parentRefs:
- name: foo
   kind: Gateway
   sectionName: "http"
-  name: foo
   kind: Gateway
   port: 80
```
is invalid.

Do you agree with this @robscott?
