### ISSUE TITLE
Support for specifying the filter execution order in HTTPRoute

### ISSUE THREAD

**Issue by Amila-Rukshan** [kubernetes-sigs/gateway-api#1598]
**What would you like to be added**:

There are scenarios where the filters should be applied in a predefined order.  But the filters does not support a way to order individual filter since it's an unordered list.

For example following HTTPRoute has multiple filters,
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route-webhook
  namespace: apk
spec:
  hostnames:
  - my.gw.org
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: Default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: web-hook-service
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /my-api/7.6.0
    filters:
      - type: ExtensionRef
        extensionRef:
            group: ""
            kind: MyPolicy
            name: my-policy-2
      - type: ExtensionRef
        extensionRef:
            group: ""
            kind: MyPolicy
            name: my-policy-1
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /2457afc0-c3c0-46a0-a389-a84025b8eabe

```

How can someone specify the order like `my-policy-1`,  `my-policy-2`, and then `urlRewrite` filters are applied in order?

Docs says this is not supported yet:  https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteFilter

> "The effects of ordering of multiple behaviours are currently unspecified.". 

We would like to have the support for this.

Any thought on this?

Thanks!

**Comment by shaneutt** [comment]
Hi @Amila-Rukshan thanks for the request. Can you help us to better understand the context and use case? What implementation(s) are you particularly interested in having implement this?

**Comment by Amila-Rukshan** [comment]
@shaneutt thanks for replying!
For example, let's say `my-policy-1` checks whether some header is available in the request and adds a default header value if is not present, and the  `my-policy-2` is the one that does the validation of that header and allowing the request going to backend from the gateway. We should have a way to handle that kind of filter dependancies.

**Comment by shaneutt** [comment]
> @shaneutt thanks for replying! For example, let's say `my-policy-1` checks whether some header is available in the request and adds a default header value if is not present, and the `my-policy-2` is the one that does the validation of that header and allowing the request going to backend from the gateway. We should have a way to handle that kind of filter dependancies.

Understood, thank you. So is this more of a user-facing request, or what implementation(s) are you hoping to add this to?

**Comment by Amila-Rukshan** [comment]
@shaneutt what about having another optional property called `order` which is a number for a filter where if defined then then it will be used for execution order.

For example:
```
apiVersion: [gateway.networking.k8s.io/v1beta1](http://gateway.networking.k8s.io/v1beta1)
kind: HTTPRoute
...
...
    filters:
      - type: ExtensionRef
        order: 2
        extensionRef:
            group: ""
            kind: MyPolicy
            name: my-policy-2
      - type: ExtensionRef
        order: 1
        extensionRef:
            group: ""
            kind: MyPolicy
            name: my-policy-1
      - type: URLRewrite
        order: 3
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /2457afc0-c3c0-46a0-a389-a84025b8eabe
```

**Comment by howardjohn** [comment]
If we need order I would think that should be defined by the order in the list

**Comment by robscott** [comment]
Thanks for brining this one back up @sanjaypujare! It looks like I missed this the first time, but I don't think there's anything about the existing filters list that makes it unordered. We simply haven't provided any guidance in the spec in terms of ordering. This was initially with the thought that many underlying dataplanes have a fixed order of operations that could not support this kind of custom ordering for at least some features. With that said, it probably makes sense to add some guidance that implementations should respect the order filters are defined in wherever possible. Each implementation should also likely document any implementation-specific limitations on filter ordering they have.

@sanjaypujare if you're up for making an update to the spec, I think it would be helpful to at least provide some recommendations here.

**Comment by sanjaypujare** [comment]
> Thanks for brining this one back up @sanjaypujare! It looks like I missed this the first time, but I don't think there's anything about the existing filters list that makes it unordered. We simply haven't provided any guidance in the spec in terms of ordering. This was initially with the thought that many underlying dataplanes have a fixed order of operations that could not support this kind of custom ordering for at least some features. With that said, it probably makes sense to add some guidance that implementations should respect the order filters are defined in wherever possible. Each implementation should also likely document any implementation-specific limitations on filter ordering they have.
> 
> @sanjaypujare if you're up for making an update to the spec, I think it would be helpful to at least provide some recommendations here.

So this is what I am thinking: I would like to change the text at https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1/httproute_types.go#L199 (and a similar one for GRPCRoute if applicable) to say something like:

"The filters are applied in the order they are listed. In case an implementation has a fixed order of operations that cannot support the listed order, the implementation will reject the whole Route with an error."

Let me know what you think. If okay, I'll open a PR.

**Comment by sanjaypujare** [comment]
There are no comments so I'll take it as there are no objections and I'll open a PR to specify list order for filters.

**Comment by robscott** [comment]
>In case an implementation has a fixed order of operations that cannot support the listed order, the implementation will reject the whole Route with an error

I personally think rejecting the Route is a bit much in this case. We could theoretically have a standard way to communicate that filters will not be executed in the order specified, but there are some cases where order doesn't really matter and the warning message may cause unnecessary confusion.

**Comment by sanjaypujare** [comment]
> ...
> I personally think rejecting the Route is a bit much in this case. We could theoretically have a standard way to communicate that filters will not be executed in the order specified, but there are some cases where order doesn't really matter and the warning message may cause unnecessary confusion.

Good point about rejecting. How about indicating through [`RouteParentStatus.Conditions`](https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1/shared_types.go#L484) ? We can use [`RouteReasonIncompatibleFilters`](https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1/shared_types.go#L353C2-L353C32) for this or I can propose a new status, say `RouteReasonIncompatibleFilterOrder` ? May be the latter one addresses the unnecessary confusion case?

**Comment by EItanya** [comment]
Maybe this is unrelated/irrelevant, but I think we have to be really careful here, especially with #713 being so widely used by the community. Let's take for example the Route above:
```
apiVersion: [gateway.networking.k8s.io/v1beta1](http://gateway.networking.k8s.io/v1beta1)
kind: HTTPRoute
metadata:
  name: http-route-webhook
  namespace: apk
...
...
    filters:
      - type: ExtensionRef
        order: 2
        extensionRef:
            group: ""
            kind: MyPolicy
            name: my-policy-2
      - type: ExtensionRef
        order: 1
        extensionRef:
            group: ""
            kind: MyPolicy
            name: my-policy-1
      - type: URLRewrite
        order: 3
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /2457afc0-c3c0-46a0-a389-a84025b8eabe
```

Not let's add some policy which applies auth to that HTTPRoute
```
apiVersion: some.gvk/v1alpha1
kind: AuthPolicy
metadata:
  name: auth-policy
  namespace: apk
spec:
  targetRef:
    name: http-route-webhook
  config:
    # insert authz config here
```

If the user wanted to ensure that `auth-policy` above would be executed at a specific point in the chain, how would they accomplish that? I can think of a couple of ways, but they feel very complex in a way that may complicate the spec more than benefit it. I'd be curious to hear from implementations how often they benefit from exposing this complexity to the user rather than exposing specific use-cases via the API.  @sanjaypujare  and I started having this discussion in #2628 as well and I'm still not convinced this is the responsibility of the spec, but rather of any implementation that wishes to expose filter ordering to it's users.
