### ISSUE TITLE
Replacing a prefix separate from the regex match

### ISSUE THREAD

**Issue by Amila-Rukshan** [kubernetes-sigs/gateway-api#1605]
I came across a scenario where we need a regex based matching for path but replace a prefix from the match. I just tried following example. 
```
spec:
...
    matches:
    - path:
        type: RegularExpression
        value: /http-bin-api/1.0.8/order/(oid\d+)
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
``` 

But I get the following error 
```
Error from server: error when creating "sample-route.yaml": admission webhook "validate.gateway.networking.k8s.io" denied the request: spec.rules[0][0].urlRewrite.path: Invalid value: "/": exactly one PathPrefix match must be specified to use this path modifier
```

It's not exactly clear what this error says to me. But I would want a scenario like this. Giving a error is fine since there is no prefix to replace as if we used `PathPrefix`. But if I had a way to specify a prefix within the `URLRewrite` filter then it is possible.

In two steps:

- Do the path matching based on regex
- Then rewrite a prefix section of that matched path 

For that I would like to have a config like below. It is same as the above except it has `prefixMatch` field which specifies the prefix to be replaced after regex matched path. 

```
spec:
...
    matches:
    - path:
        type: RegularExpression
        value: /http-bin-api/1.0.8/order/(oid\d+)
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          prefixMatch: /http-bin-api/1.0.8
          replacePrefixMatch: /
``` 

Sample input and output will be as below:

input:  `/http-bin-api/1.0.8/order/oid1203`
output: `/order/oid1203`

I would like this kind of combination to be supported.

Any thoughts or plan to support this kind of feature. I came across this [RequestRewrite](https://gateway-api.sigs.k8s.io/geps/gep-726/?h=regex#future-extension) filter but it does not include this scenario.  

Thanks!
