### ISSUE TITLE
HTTPRoute set a timeout

### ISSUE THREAD

**Issue by itetradev** [kubernetes-sigs/gateway-api#1612]
**What would you like to be added**:
I would like an option to set a custom timeout.  I have only found [this comment](https://github.com/kubernetes-sigs/gateway-api/issues/1074#issuecomment-1086396888) referencing timeout saying that they aren't supported. It mentions an alternative of how to implement them but the link provided just leads to a 404 page.

**Why this is needed**:
I have a WebSocket API and I need to increase the default timeout of 30s of HTTPRoute. It is not compatible with WebSockets as it drops the connection every 30s.

**Comment by shaneutt** [comment]
Is this for a specific implementation which you're _using_, or is this something you're trying to _implement_?

**Comment by itetradev** [comment]
@shaneutt It's for an implementation I am using. Here is the yaml for my HTTPRoute:

```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: public-store-route
  namespace: namespace
  labels:
    gateway: external-http
spec:
  hostnames:
  - "my-website.example.org"
  parentRefs:
  - name: external-http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /west
    backendRefs:
    - group: net.gke.io
      kind: ServiceImport
      name: store-west-1
      port: 8080
```

The service `store-west-1` is a REST API that has a WebSocket connection. The current default timeout is 30 seconds and after 30 seconds my WebSocket connection drops out. 

I just want the option to be able to increase the timeout from the default 30 seconds to allow me to keep the WebSocket open for a longer time.

**Comment by shaneutt** [comment]
Understood. At present, we consider things like timeouts to be `implementation-specific` and _suggest_ a `Policy`-type API be provided by implementations for these kinds of things, see:

https://gateway-api.sigs.k8s.io/references/policy-attachment/

So if you can tell me _which_ implementation your using I might be able to help determine how (and I suppose if) they implemented this and where the documentation is for that.

**Comment by itetradev** [comment]
Ah, I understand. That makes sense to me now. Sorry for my stupidity earlier.

So I am using the `gateway.networking.k8s.io/v1beta1` implementation (I think that's what you are asking).  I was also looking at policy API (They have called it LBPolicy) but it doesn't seem to be working for me.  This is my gateway configuration:

```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: external-http
  namespace: namespace
spec:
  addresses:
      - value: ext-gw
        type: NamedAddress
  gatewayClassName: gke-l7-gxlb-mc
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: my-cert
```

I have tried to use the `LBPolicy` with the `targetRef` being the `Gateway`, `HTTPRoute`, `Service`, or `ServiceImport` and nothing seemed to change the timeout for me. Here is an example of the `LBPolicy` that I was trying to set up:

```
kind: LBPolicy
apiVersion: networking.gke.io/v1
metadata:
  name: gateway-timeout-policy
  namespace: namespace
spec:
  default:
    timeoutSec: 86400
  targetRef:
    name: external-http
    group: gateway.networking.k8s.io
    kind: Gateway
```

Here is a link to the GCP documentation that I've found:
https://cloud.google.com/kubernetes-engine/docs/how-to/configure-gateway-resources

Am I missing some step here?
