### ISSUE TITLE
Race condition in route update status with different gateway controllers

### ISSUE THREAD

**Issue by ivanmatmati** [kubernetes-sigs/gateway-api#1629]
**What happened**:
I was in the process of implementing the tcproute status management in our gateway controller and I realized  that as any route can refer to multiple and different gateways there could be a race condition in the update of status.

**What you expected to happen**:
A merge operation should happen to deal with multiple and different sources of status updates (= different controllers).

**How to reproduce it (as minimally and precisely as possible)**:
For example, suppose we deal with this route:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: route1
  namespace: ns1
spec:
  parentRefs:
    - name: mygateway
    - name: othergateway
  rules:
    - backendRefs:
        - kind: Service
          name: tcp-echo-server
          port: 9000
```
`mygateway` is managed by my controller but not `othergateway`. At the creation of this route, my controller and the controller of the other vendor will try to update the status of this route with a likely race condition.

**Anything else we need to know?**:
