### ISSUE TITLE
GEP: Standard Mechanism to Merge Multiple Gateways 

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/gateway-api#1713]
**What would you like to be added**:

Support for merging Gateways should have standard & documented mechanic.

**Why this is needed**:

> Prior Discussions: https://github.com/kubernetes-sigs/gateway-api/discussions/1248, https://github.com/kubernetes-sigs/gateway-api/discussions/1246

Knative generates on demand per-service certificates using HTTP-01 challenges. There can be O(1000) Knative Services in the cluster which means we have O(1000) distinct certificates. The Gateway Resource is a contention point since is the only place to attach listeners to gateways with certificates.

The spec currently has language to indicate implemenations `MAY` merge Gateways resources but the mechanic isn't defined. 
https://github.com/kubernetes-sigs/gateway-api/blob/541e9fc2b3c2f62915cb58dc0ee5e43e4096b3e2/apis/v1beta1/gateway_types.go#L76-L78

Secondly, given similar use-cases/needs for control planes to manage listeners it might make sense that `merging` Gateways is part of `extended` conformance.

**Comment by arkodg** [comment]
+1 to this proposal. 

* This has been asked by users of Envoy Gateway to make their runtime deployments more efficient (currently a  `Gateway` resource maps to a unique Data Plane (Envoy Proxy) deployment)

* The spec says compatible listeners can be collapsed, but since `Gateways` can be applied dynamically  
it is bound to cause traffic disruption in the data plane if the implementation collapses or separates listener implementations in runtime.

* If there is way to add a knob which sets constraints for the L3/L4 fields of the `Listener` such as ensuring a port must be unique across all `Listeners` within all `Gateways` within a `GatewayClass`, statically collapsing listeners in implementations should be doable. 
Below is the current spec
https://github.com/kubernetes-sigs/gateway-api/blob/0177808c57566502f8fb697abd6d42c06008ff6a/apis/v1beta1/gateway_types.go#L72

**Comment by howardjohn** [comment]
FWIW how we do this in Istio is https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment. Basically the same way to apply 1 Gateway to a manually deployed Deployment/Service instead of automatically deployed one can be used to apply N Gateways and merge them.

If they want automated deployment and merging, they would make one "root" Gateway and attach all others. Actually that is another use case for https://github.com/kubernetes-sigs/gateway-api/pull/1596

**Comment by arkodg** [comment]
@howardjohn [conformance tests](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/base/manifests.yaml#L16-L62) dont pass when the implementation merges the listeners, https://github.com/envoyproxy/gateway/issues/349 has more context

**Comment by howardjohn** [comment]
I don't think something implicitly deciding to collapse or not is a great idea which is the root cause of that. In the Istio way users have to explicitly opt into merging, which the conformance tests don't do, so we don't have an issue.

**Comment by arkodg** [comment]
> I don't think something implicitly deciding to collapse or not is a great idea which is the root cause of that. In the Istio way users have to explicitly opt into merging, which the conformance tests don't do, so we don't have an issue.

yeah, Im hoping the intent to merge is defined by Gateway API, else implementations will add their own

**Comment by dprotaso** [comment]
@shaneutt curious what does the label `priority/awaiting-more-evidence` mean and what's the lifecycle of issues in this sub project?

**Comment by shaneutt** [comment]
@dprotaso we're in the midst of trying to better organize things based on priority. Given that 3 people are interested in this one, `priority/awaiting-more-evidence` was not really the right fit so I've changed it to `priority/important-longterm`. Please note that while these labels can be helpful for us to organize work and releases, they aren't necessarily indicative of the actual order in which things will be done. It's reasonable for someone with keen interest to champion an issue like this and take it straight into `in-progress` if they feel strongly about it.

**Comment by dprotaso** [comment]
@arkodg 

> The spec says compatible listeners can be collapsed, but since Gateways can be applied dynamically
it is bound to cause traffic disruption in the data plane if the implementation collapses or separates listener implementations in runtime.

Knative uses multiple Kubernetes Services to resolve port conflicts.

Our custom Istio installation has a single k8s deployment serving public traffic and internal traffic. This is because we create one K8s Service with `type=LoadBalancer` and the other being `type=ClusterIP` pointing to the same deployment but targetting different ports.

Thus if the Gateway resource had a `scope` property to define whether gateways were public (to the internet) and local to the cluster then I could forsee merging of

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: prod-internal
spec:
  gatewayClassName: acme-lb
  group: knative
  scope: Internal
  listeners:  
  - protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: prod-web
spec:
  gatewayClassName: acme-lb
  group: knative
  scope: Public
  listeners:  
  - protocol: HTTP
    port: 80
```

to be done by creating the following K8s Services

```yaml
apiVersion: v1
kind: Service
metadata:
   name: prod-internal
spec:
  type: ClusterIP
  ports:
    - name: http2
      port: 80
      targetPort: 8081 # Dynamically allocated port
---
apiVersion: v1
kind: Service
metadata:
   name: prod-web
spec:
  type: LoadBalancer
  ports:
    - name: http2
      port: 80
      targetPort: 80 # Dynamically allocated port
```

Each gateway could return a unique IP in the `status.addresses` block.
