### ISSUE TITLE
GRPCRoute match defaulting prevents matching all requests

### ISSUE THREAD

**Issue by skriss** [kubernetes-sigs/gateway-api#1751]
**What happened**:

Created a `GRPCRoute` like the following:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpcroute
spec:
  parentRefs:
  - name: gateway
  rules:
  - backendRefs:
    - name: grpc-echo
      port: 9000
```
With the intention of matching all requests, [per the spec](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1alpha2.GRPCRouteRule):

> If no matches are specified, the implementation MUST match every gRPC request.

This GRPCRoute then ended up not being Accepted by my implementation, because [the API defaulting added a default method match](https://github.com/kubernetes-sigs/gateway-api/blame/main/apis/v1alpha2/grpcroute_types.go#L208), with no service or method specified, which is [not a valid configuration](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.GRPCMethodMatch):
> At least one of Service and Method MUST be a non-empty string.

**What you expected to happen**:
I think this default should be removed; specifying no matches is valid configuration for matching all requests and should be left as-is.

If folks agree this should be changed, I'll submit a PR for it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
