### ISSUE TITLE
Match multiple methods in HTTPRouteMatch

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/gateway-api#1785]
**What would you like to be added**:
https://github.com/kubernetes-sigs/gateway-api/blob/f8442221c60b186c23560232ffa65803a5d09278/apis/v1beta1/httproute_types.go#L546

It will be better DX to support multiple method matches in HTTPRouteMatch

`Method []HTTPMethod `json:"method,omitempty"``

**Why this is needed**:

While this can be done using multiple match rules, it is better DX to support `[]HTTPMethod`. Also, the other matches (header, query params) support array. So, it will be also more consistent.

Similar issue also exists in GRPC api.

**Comment by youngnick** [comment]
I think this is a reasonable request, but unfortunately, it's a breaking API change, so we'll probably need to add a plural field (i.e. `Methods` instead of `Method`, with semantics for cross-populating `Method` into `Methods` etc). This sucks to some extent but we don't want to make a breaking API change for HTTPRoute at this point, sadly.

**Comment by youngnick** [comment]
The upstream reference on the right way to make a singular field plural is https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#making-a-singular-field-plural

**Comment by shaneutt** [comment]
> The upstream reference on the right way to make a singular field plural is https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#making-a-singular-field-plural

So it would seem this is doable, albeit it's not going to be simple or quick. Marking this as accepted and giving it a priority for now and we'll allow some time to see if anyone wants to take it on:

/remove-triage
/priority backlog
/help

**Comment by mindw** [comment]
DRY - Example of how restricting a route to certain HTTP methods will look like after making `method` plural.
After:
```
  rules:
  - backendRefs:
    - name: my-service
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /api/my-service/
      # Per making-a-singular-field-plural above - that plural[0] must match the singular value.
      method: GET
      methods:
      - GET
      - HEAD
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
```

Now:
```
  rules:
  - backendRefs:
    - name: my-service
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /api/my-service/
      method: GET
    - path:
        type: PathPrefix
        value: /api/my-service/
      method: HEAD
    - path:
        type: PathPrefix
        value: /api/my-service/
      method: POST
    - path:
        type: PathPrefix
        value: /api/my-service/
      method: PUT
    - path:
        type: PathPrefix
        value: /api/my-service/
      method: DELETE
    - path:
        type: PathPrefix
        value: /api/my-service/
      method: PATCH
    - path:
        type: PathPrefix
        value: /api/my-service/
      method: OPTIONS

```
