### ISSUE TITLE
Listener name must be unique within a Gateway

### ISSUE THREAD

**Issue by muyuan0** [kubernetes-sigs/gateway-api#1845]
**What happened**:

According to https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.Listener

> Name is the name of the Listener. This name MUST be unique within a Gateway.

However, it seems gateway-api doesn't check the name currently.

**What you expected to happen**:

The listener with the duplicate name should be rejected.

**How to reproduce it (as minimally and precisely as possible)**:

A configuration like this can be incorrectly accepted:
```
  kind: Gateway
  metadata:
    namespace: envoy-gateway
    name: gateway-1
  spec:
    gatewayClassName: envoy-gateway-class
    listeners:
    - name: http-1
      protocol: HTTP
      port: 8080
    - name: http-1
      protocol: HTTP
      port: 80

```

**Anything else we need to know?**:

The issue is originally raised at https://github.com/envoyproxy/gateway/issues/1180 and I have provided an initial fix in https://github.com/envoyproxy/gateway/pull/1181. I could rewrite the fix to adapt gateway-api's code if the report is accepted.
