### ISSUE TITLE
Provide Additional Granularity in BackendRef Selection

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#1861]
**What would you like to be added**:
Currently, matched requests are routed to a list of [BackendRefs](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.BackendRef). I would like the ability to provide additional backend selection granularity before routing a request. In many implementations, the request is not routed directly to the referenced object. Instead, the referenced object is used to query other objects for making a routing decision.

**Why this is needed**:
As an App Owner, I need the ability to canary upgrade a Service that is referenced by a `backendRef` without requiring a separate Service per app version.

The following example demonstrates how BackendRef currently supports a canary upgrade, where each BackendRef is a separate Service:
```yaml
kind: HTTPRoute
...
  rules:
  - backendRefs:
    - name: foo-v1
      port: 8080
      weight: 90
    - name: foo-v2
      port: 8080
      weight: 10
```

The above example sends 90% of the proportion of matched requests to Service "foo-v1" and 10% to Service "foo-v2". However, it's common that an app consists of multiple Deployments (based on the app version) with a single Service.

**Comment by danehans** [comment]
cc: @youngnick @mikemorris @kflynn since you mentioned this is a feature you may be interested in.

I'm happy to lead a GEP if it garners enough support. A few approaches that come to mind are:
- Add a `selector` field to BackendRef that is a label selector. If specified, the labels specified by `selector` can be used when making a forwarding decision. A similar concept is already being used by Gateway for route namespace selection.
- Add a `filters` field to BackendRef for providing a more generalized approach to routing traffic.

**Comment by howardjohn** [comment]
One thing I think would be prudent to discuss in the GEP would be to indicate why we need this vs just creating more services to group things

**Comment by danehans** [comment]
> just creating more services to group things

^ approach would require a change to the app, correct? Take the following example:

```yaml
apiVersion: v1
kind: Service
metadata:
name: helloworld
labels:
  app: helloworld
spec:
  selector:
    app: helloworld
  ...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - image: helloworld-v1
        ...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v2
    spec:
      containers:
      - image: helloworld-v2
        ...
```

This example exposes 2 version of the helloworld app using a single VIP and DNS name, i.e. ClusterIP. If I create a second Service and update the labels/selectors to support BackendRef traffic splitting, I have two separate VIPs and DNS names for the helloworld app. I am now responsible for changing external load balancing, DNS resolution, etc.
