### ISSUE TITLE
Clarification on behavior for duplicate parent refs for routes.

### ISSUE THREAD

**Issue by jm96441n** [kubernetes-sigs/gateway-api#1925]
**What would you like to be added**:
An additional conformance test specifying the behavior when a gateway has only a single listener and an http route specifies the gateway twice: once in specifying the gateway with the listener and once without specifying the specific listener. According to the [docs](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.CommonRouteSpec) this should result in an invalid route configuration. 

This feels like a potentially uncovered edge case in the docs as it is neither two _identical_ parents (as could be detected by the webhook) nor two distinct sections, and _might_ be a valid configuration if the Gateway had a second listener which could match the parentRef not specifying a listener name.

**Why this is needed**:
To clarify the above behavior for implementers  of the gateway spec.

**Comment by shaneutt** [comment]
Sounds good, lined this up for our next release (though it may flood over into `v0.8.0` ultimately) and if there's a contributor that would like to jump in and help with this one it would be very appreciated!

/help

**Comment by shaneutt** [comment]
> I wouldn't mind writing the tests themselves, more looking for clarification on what the expected behavior is here.

Awesome, appreciate the interest! For extra clarity, can you provide an example YAML configuration of the currently ambiguous situation?

**Comment by jm96441n** [comment]
hey @shaneutt sorry this took a little bit to get back to you on, below is a yaml configuration that shows the ambiguous situation:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: apigw
spec:
  gatewayClassName: api-gateway
  listeners:
  - name: http-listener
    protocol: HTTP
    port: 30002
    hostname: '*.example.com'
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route
spec:
  hostnames:
    - ref.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: apigw
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: apigw
      sectionName: http-listener
  rules:
    - backendRefs:
      - kind: Service
        name: some-service
        port: 80
        weight: 1
      matches:
      - path:
          type: PathPrefix
          value: /
```

so this HTTPRoute references the same gateway twice, but specifies the listener in one parent ref and does not specify it in the other ref. This could be a potentially valid situation _if_ the gateway had more than one listener.
