### ISSUE TITLE
Allow Redirects to Drop Trailing Slash

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1954]
**What would you like to be added**:
A way to configure a redirect to drop a trailing slash.

**Why this is needed**:
Today our redirect filter makes it seem like this should maybe be possible, for example this gets kinda close:

```yaml
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  hostnames:
  - example.com
  rules:
  - matches:
    - path:
        type: Exact
        value: /example/
    filters:
    - type: RequestRedirect
      requestRedirect:
        statusCode: 302
        path:
          type: ReplaceFullPath
          replacePrefixMatch: /example
```

Unfortunately an implementation of this config _might_ result in a redirect loop depending on what we decide in https://github.com/kubernetes-sigs/gateway-api/issues/1953. Even if it did work, it's still not as easy as it should be to do that. At a minimum, we should clarify whether this works. We should also consider providing a better more scalable way to do this even if this way may technically work.

**Comment by tonygilkerson** [comment]
with this would I also be able to do the following?

```
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  hostnames:
  - example.com
  rules:
  - matches:
    - path:
        type: Exact
        value: /api/
    filters:
    - type: RequestRedirect
      requestRedirect:
        statusCode: 302
        path:
          type: ReplaceFullPath
          replacePrefixMatch: /
```

So that a request for `/api/foo` and `/api/bar` become `/foo` and `/bar`?   When I try this today I get `//foo` and `//bar`

**Comment by robscott** [comment]
@tonygilkerson As long as it's broadly implementable, I think that needs to be in scope for whatever is proposed here.

**Comment by JackPott** [comment]
I have observed the same behavior as @tonygilkerson, which feels like a bug to me. If one sets `replacePrefixMatch: ""` the rule disables complete, but with `replacePrefixMatch: /` its rewriting `/foo/bar` into `//bar`, which my upstream rejects as a bad request. 
- `/foo` becomes `/` which seems correct
- `foo/` becomes `//` 
- `foo/bar` becomes `//bar`
- `/foo/bar/` becomes `//bar/`

Workaround is have one rule for `/foo -> /` and another for `/foo/bar -> /bar` but this has obvious drawbacks.

This is using Istio gateway as the implementation, unclear if this is their interpretation of the API?

**Comment by janeklb** [comment]
This is particularly confusing since the docs for `HTTPPathModifier` (https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPPathModifier) have a table of examples, which seem to be incorrect

![image](https://github.com/kubernetes-sigs/gateway-api/assets/877396/beaf74ef-7938-4ea6-b108-bade0e22950e)

**Comment by shaneutt** [comment]
Where are we at with this one?

**Comment by Demonsthere** [comment]
Bumping thread as we experience the same issue:
```yaml
  - filters:
    - requestRedirect:
        path:
          replacePrefixMatch: /
          type: ReplacePrefixMatch
        port: 8080
        scheme: https
        statusCode: 301
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /api/foo/public/
```

In the given example we want to simply delete the whole Prefix, replace it with `/`.  However what we see happening is a double slash:

```shell
GET https://REDACTED/api/foo/public/bar
      accept: application/json
      accept-encoding: gzip,deflate,br
    ← 301 Moved Permanently
      transfer-encoding: chunked
      connection: close
      location: https://REDACTED:8080//bar
```

We have tried fixing that with a clienttrafficpolicy:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: proxy
spec:
  path:
    disableMergeSlashes: false
```

But that didn't remove the double slash as expected
