### ISSUE TITLE
Support `connectionPool` and `loadBalancer` from Gateway to Backend

### ISSUE THREAD

**Issue by machine3** [kubernetes-sigs/gateway-api#2005]
**What would you like to be added**:
Support connectionPool and loadBalancer from Gateway to Backend. Just like Istio DestinationRule
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-destination-rule
spec:
  host: my-svc
  trafficPolicy: 
    connectionPool: <-- here
    loadBalancer:  <-- here
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
    trafficPolicy: 
      connectionPool: <-- here
      loadBalancer:  <-- here
  - name: v3
    labels:
      version: v3

```

**Why this is needed**:
