### ISSUE TITLE
conformance: echoserver logging and shutdown is insufficient

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#2011]
echoserver logs are very sparse. For example: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/44861/integ-cni_istio/1656532051194548224/artifacts/pilot-db897f21a3214f5399a68bd4e/TestGatewayConformance/_test_context/gateway-conformance-infra-state2110935622/primary-0/infra-backend-v2-74fdd9c89f-k5dlv_infra-backend-v2.log

This makes it hard to debug, as we don't even have timestamps on the logs.

The shutdown logic is also not sufficient. When it gets a SIGTERM, it exists with a non-zero exit code unexpectedly. This, in turn, triggers our tests to send alerts as we don't want pods to fail in our tests.

Example of the Pod after shutdown:

```yaml
  containerStatuses:
  - containerID: containerd://f61d2e6ee6ba6d4c0fe860dbaccf54a4460067ab8c53c3113daf8a3d7ff019b3
    image: gcr.io/k8s-staging-ingressconformance/echoserver:v20221109-7ee2f3e
    imageID: gcr.io/k8s-staging-ingressconformance/echoserver@sha256:fa56a9251de6408c474d70a40f6cbf19c30954bb97dc1e6dfd5a3c9911b6991f
    lastState: {}
    name: infra-backend-v1
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://f61d2e6ee6ba6d4c0fe860dbaccf54a4460067ab8c53c3113daf8a3d7ff019b3
        exitCode: 2
        finishedAt: "2023-05-11T16:17:07Z"
        reason: Error
        startedAt: "2023-05-11T16:16:34Z"
```
