### ISSUE TITLE
HTTPRoute RequestRedirect Issue

### ISSUE THREAD

**Issue by Sovenique** [kubernetes-sigs/gateway-api#2095]
Greetings, 

I'm using `0.7.1` CRDs alongside with Istio `1.17.2` in a Kubeadm `1.26.4` Cluster, so I'm leveraging Istio's Envoy as the GatewayClass. 

So this is my Gateway object, I have 2 listeners, one per HTTP/HTTPS:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: global-gateway
  namespace: istio-gateway
  labels:
    istio: global-gateway
  annotations:
    networking.istio.io/service-type: "NodePort"
spec:
  gatewayClassName: istio
  listeners:
  - name: global-http
    hostname: "*.example.com"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: "default"
  - name: global-https
    hostname: "*.example.com"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: wildcard-ssl-secret
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: "default"
  ```
  
 After this point, I'm applying a HTTPRoute for a service I want to expose. In addition to that, this object includes the `RequestRedirect` filter so all HTTP requests get redirected to HTTPS for this specific service.
 
 
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: service-route
  namespace: default
spec:
  hostnames:
  - "service.example.com"
  parentRefs:
  - name: global-gateway
    namespace: istio-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
          port: 443
    backendRefs:
    - name: service
      port: 8000
 ```
 
The expected outcome is get a 301 when initiating a `HTTP` request and a 200 for `HTTPS`.
 
This works as expected for `HTTP`. 
 
```
curl -s -I "http://service.example.com"

HTTP/1.1 301 Moved Permanently
location: https://service.example.com:443/
date: Tue, 06 Jun 2023 10:39:08 GMT
transfer-encoding: chunked
```

But not for `HTTPS`, I'm getting a 301 instead of 200:

```
curl -s -I "https://service.example.com"

HTTP/2 301
location: https://service.example.com:443
date: Tue, 06 Jun 2023 10:39:16 GMT
```

I've tried different variations of the HTTPRoute or creating an exlcusive HTTPRoute for the redirect filter, but I can't make it work properly. As I workaround I created 2 seperate Gateway objects per protocol and 2 HTTPRoute objects in order to make it work as expected.

Am I missing something?

Thank you so much for your time!

**Comment by howardjohn** [comment]
The HTTPRoute applies to both listeners. It is not conditional based on whether the original request was HTTP or not. You will need 2 routes

**Comment by Sovenique** [comment]
Hey @howardjohn,

Thanks for replying.

I've tried this approach, the redirect works for HTTP listener but the HTTPS listener still returns a 301 response. Hope I haven't misconfigured something.

```
kind: HTTPRoute
metadata:
  name: service-route-http
  namespace: default
spec:
  hostnames:
  - "service.example.com"
  parentRefs:
  - name: global-gateway
    namespace: istio-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
        statusCode: 301
    backendRefs:
    - name: service
      port: 8000
 ```
 
 ```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: service-route-https
  namespace: default
spec:
  hostnames:
  - "service.example.com"
  parentRefs:
  - name: global-gateway
    namespace: istio-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: service
      port: 8000
      ```
      
 ```
 curl -s -I "http://service.example.com"

HTTP/1.1 301 Moved Permanently
location: https://service.example.com:443/
date: Tue, 06 Jun 2023 15:12:57 GMT
transfer-encoding: chunked
```
```
curl -s -I "https://service.example.com"

HTTP/2 301
location: https://service.example.com:443/
date: Tue, 06 Jun 2023 15:13:06 GMT
```
