### ISSUE TITLE
Validation Should Prevent Redirect Filters and BackendRefs in same HTTPRoute Rules

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2148]
**What happened**:
HTTPRoute validation allows the following YAML through:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-rewrite
spec:
  hostnames:
    - rewrite.example
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
      backendRefs:
        - name: example-svc
          port: 80
```

**What you expected to happen**:
Webhook validation to prevent that invalid configuration because BackendRefs are not valid in the same HTTPRoute rule as a RequestRedirect filter.

**Anything else we need to know?**:
This validation should be added roughly in this vicinity: https://github.com/kubernetes-sigs/gateway-api/blob/a5ede12430c31639349ae6c00666890591f72a40/apis/v1beta1/validation/httproute.go#L54

Once the validation is in place, add the example above to https://github.com/kubernetes-sigs/gateway-api/tree/a5ede12430c31639349ae6c00666890591f72a40/hack/invalid-examples/v1beta1/httproute.
