### ISSUE TITLE
support HTTPHeaderFilter.Set after choosing backend

### ISSUE THREAD

**Issue by robberphex** [kubernetes-sigs/gateway-api#2165]
**What would you like to be added**:

The capacity to set header after choosing backend.

**Why this is needed**:

For example, the follow rule:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: simple-route
spec:
  rules:
  - filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        set: 
          - name: env
            value: v1
    backendRefs:
    - name: foo-v1
      port: 8080
      weight: 90
    - name: foo-v2
      port: 8080
      weight: 10
```

Is there any way to set header `env=v1` when call foo-v1, and set header `env=v2` when call foo-v2?

**Comment by robscott** [comment]
Hey @robberphex, the API _technically_ allows this, but I'm not sure if any implementations support this. BackendRefs on HTTPRoute support filters, but support at that level is only implementation-specific:

https://github.com/kubernetes-sigs/gateway-api/blob/f883de997b88dd6ee138930198542da8a9b2f634/apis/v1beta1/httproute_types.go#L1039-L1047

So technically something like this should be representable in the API, but unsure which implementations support it:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: simple-route
spec:
  rules:
  - backendRefs:
    - name: foo-v1
      port: 8080
      weight: 90
      filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          set: 
            - name: env
              value: v1
    - name: foo-v2
      port: 8080
      weight: 10
```
