### ISSUE TITLE
gateway-api-admission-server requires a restart after tls certificate renewal

### ISSUE THREAD

**Issue by rkosyk** [kubernetes-sigs/gateway-api#2167]
**What happened**:

We are using cert-manager to generate and renew short-term tls certificates instead of gateway-api-admission create and patch kubernetes jobs.
After the certificate is renewed in secret and the old certificate is expired I need to restart gateway-api-admission-server, otherwise, I am getting the error about certificate expiration when trying to create Gateway API custom resources:
> Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": failed to call webhook: Post "https://gateway-api-admission-server.gateway-api.svc:443/validate?timeout=10s": x509: certificate has expired or is not yet valid

**What you expected to happen**:

gateway-api-admission-server should pick up a new certificate without a manual restart of the admission-server pod

**How to reproduce it (as minimally and precisely as possible)**:
1. Generate short-term tls certificates in gateway-api-admission secret and restart admission server
2. Wait until the certificate expired and generate a new certificate in secret
3. Try to create Gateway custom resource and see the error about certificate expiration 

**Anything else we need to know?**:

- Webhook version - 0.7.1
- Used Kubernes manifests from here to install gateway-api crds and webhook (except gateway-api-admission create and patch kubernetes jobs)
  https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/experimental-install.yaml
- Kubernetes version - 1.23.17
- Gateway Controller used to create Gateway API resources - Envoyproxy Gateway v0.4.0
  https://github.com/envoyproxy/gateway

**Comment by gyohuangxin** [comment]
I'd like to investigate this issue. I want to reproduce it in my environment, @rkosyk could you please show the steps you used cert-manager to generate and renew short-term tls certificates instead of gateway-api-admission create and patch kubernetes jobs?

**Comment by rkosyk** [comment]
@gyohuangxin 
This **Certificate** custom resource is used to generate and renew the certificate in **gateway-api-admission** secret

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-api-admission
  namespace: gateway-api
spec:
  commonName: gateway-api-admission-server.gateway-api.cluster.local
  dnsNames:
  - gateway-api-admission-server.gateway-api.svc
  duration: 24h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: root-selfsigned-cluster-issuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  renewBefore: 12h0m0s
  secretName: gateway-api-admission
  usages:
  - server auth

```

**gateway-api-admission** secret is mapped using volumes and volumeMounts into the gateway-api-admission-server pod as cert and key files.

```
apiVersion: v1
kind: Pod
metadata:
spec:
  containers:
  - args:
    - -logtostderr
    - --tlsCertFile=/etc/certs/cert
    - --tlsKeyFile=/etc/certs/key
    - -v=10
    - 2>&1
    volumeMounts:
    - mountPath: /etc/certs
      name: webhook-certs
      readOnly: true
  volumes:
  - name: webhook-certs
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: cert
      - key: tls.key
        path: key
      secretName: gateway-api-admission

```

**Comment by gyohuangxin** [comment]
@rkosyk Thank you for the examples, but I have some issues trying to reproduce it in my environment.
My steps are as follows:
1. Install gateway-api:
```
$ kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/experimental-install.yaml
```
2. Install cert-manage via helm:
```
$ helm repo add jetstack https://charts.jetstack.io
$ helm repo update
$ helm install   cert-manager jetstack/cert-manager   --namespace cert-manager   --create-namespace   --version v1.12.0   --set installCRDs=true
```
3. Create the CA issuer and self-signed certificate
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-gateway-api-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-api-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: gateway-api-admission-server
  dnsNames:
  - gateway-api-admission-server
  secretName: gateway-api-ca-selfsigned
  issuerRef:
    name: selfsigned-gateway-api-issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateway-api-ca-issuer
spec:
  ca:
    secretName: gateway-api-ca-selfsigned
```
4. Create the certificate and map the secret using volumes and volumeMounts into the gateway-api-admission-server pod (almost the same as your example)
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-api-renew
  namespace: gateway-system
spec:
  commonName: gateway-api-admission-server.gateway-system.cluster.local
  dnsNames:
  - gateway-api-admission-server.gateway-system.svc
  secretName: gateway-api-renew
  duration: 4h0m0s
  renewBefore: 2h0m0s
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  issuerRef:
    name: gateway-api-ca-issuer
    kind: ClusterIssuer
```
```
apiVersion: v1
kind: Pod
metadata:
    spec:
      containers:
      - args:
        - -logtostderr
        - --tlsCertFile=/etc/certs/cert
        - --tlsKeyFile=/etc/certs/key
        - -v=10
        - 2>&1
        volumeMounts:
        - mountPath: /etc/certs
          name: webhook-certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: cert
          - key: tls.key
            path: key
          secretName: gateway-api-renew
```
5. But when I applied the gateway resource, I faced the issue:
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": failed to call webhook: Post "https://gateway-api-admission-server.gateway-system.svc:443/validate?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": failed to call webhook: Post "https://gateway-api-admission-server.gateway-system.svc:443/validate?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Did I miss something? @rkosyk

**Comment by rkosyk** [comment]
Yes, also you need to change ValidatingWebhookConfiguration settings to make a TLS connection with the gateway-api-admission-server. You need to set clientConfig.caBundle -  is a PEM-encoded CA bundle that will be used to validate the webhook’s server certificate.
Take a look at my working example:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gateway-api-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJjRENDQVJlZ0F5SUJBZ0lSQU45VEUvSCt0Wk84aTRnSi9kalNGVXN3Q2dZSUtvWkl8ajBFQXdJd0dERVcKTUJRR0ExVUVBeE1OWTJ4MWMzUmxjaTVzYjJOaGJEQWVGdzB5TXpBMk1UTXhNVEl3TlRaYUZ3MHpNekEyTVRBeApNVEl3
TlRaYU1CZ3hGakFVQmdOVkJBTVREV05zZFhOMFpYSXViRzlqWVd3d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxCmhrak9QUU1CQndOQ0FBUlkwalY4azAxbFFjUVNNVnRzMDgxSVZGNlE5eXVEa0RFNXNCR2VzWnJWTUZMMzZENUUKTTd4SFdpZXV3V0pVbHU1NHNnMzJHSjI2QkNVMnFqL0pyUFdubzBJd1FEQU9CZ0
5WSFE4QkFmOEVCQU1DQWdRdwpEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVNVHlqbzVVRDBMUzJGMU5WeTlnQzNFTjRQcFV3CkNnWUlLb1pJemowRUF3SURSd0F3UkFJZ1FhaWZEaVl1ckZQNllJaFZlYTB1djVwbVhVTDJHZ0kzWFRHTzlyNzIKYlBjQ0lBUHp6Q3NWdnl3M2kxc2xyV1NV
VXdiZ2NDSkRoSmdSVWt6WEpEZzJKSG5hCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: gateway-api-admission-server
      namespace: gateway-api
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate.gateway.networking.k8s.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - v1alpha2
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - gatewayclasses
    - httproutes
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

**Comment by gyohuangxin** [comment]
@rkosyk Thank you so much! I'll try it.

**Comment by gyohuangxin** [comment]
When I apply this certificate, I do see the CertificateRequests every 2 hours:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-api-renew
  namespace: gateway-system
spec:
  commonName: gateway-api-admission-server.gateway-system.cluster.local
  dnsNames:
  - gateway-api-admission-server.gateway-system.svc
  secretName: gateway-api-renew
  duration: 4h0m0s
  renewBefore: 2h0m0s
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  issuerRef:
    name: gateway-api-ca-issuer
    kind: ClusterIssuer
```
```
root@huangxin:~# kc get certificaterequest -A
NAMESPACE        NAME                      APPROVED   DENIED   READY   ISSUER                  REQUESTOR                                         AGE
gateway-system   gateway-api-renew-2gwr6   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   25h
gateway-system   gateway-api-renew-49b2r   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   31h
gateway-system   gateway-api-renew-4pcs8   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   23h
gateway-system   gateway-api-renew-9rrdq   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   37h
gateway-system   gateway-api-renew-9vrrx   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   83m
gateway-system   gateway-api-renew-br88n   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   11h
gateway-system   gateway-api-renew-bwzc6   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   27h
gateway-system   gateway-api-renew-ctnd6   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   3h23m
gateway-system   gateway-api-renew-ghmr6   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   19h
gateway-system   gateway-api-renew-hcsrz   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   13h
gateway-system   gateway-api-renew-jhr9g   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   39h
gateway-system   gateway-api-renew-lv856   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   15h
gateway-system   gateway-api-renew-qdgnm   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   21h
gateway-system   gateway-api-renew-t6n8s   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   7h23m
gateway-system   gateway-api-renew-tdbs5   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   9h
gateway-system   gateway-api-renew-vlpl7   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   41h
gateway-system   gateway-api-renew-wm24x   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   29h
gateway-system   gateway-api-renew-xtxgm   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   17h
gateway-system   gateway-api-renew-z9rrz   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   33h
gateway-system   gateway-api-renew-zlxxq   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   35h
gateway-system   gateway-api-renew-zr7qz   True                True    gateway-api-ca-issuer   system:serviceaccount:cert-manager:cert-manager   5h23m
```
However, I found the content of secret gateway-api-renew never change. And the cert-manager pod shows the logs: 
```
I0817 00:50:37.001729       1 trigger_controller.go:194] "cert-manager/certificates-trigger: Certificate must be re-issued" key="gateway-system/gateway-api-renew" reason="Renewing" message="Renewing certificate as renewal was scheduled at 2023-08-17 00:50:37 +0000 UTC"
I0817 00:50:37.001821       1 conditions.go:203] Setting lastTransitionTime for Certificate "gateway-api-renew" condition "Issuing" to 2023-08-17 00:50:37.00179997 +0000 UTC m=+232701.980289990
I0817 00:50:37.125516       1 controller.go:162] "cert-manager/certificates-key-manager: re-queuing item due to optimistic locking on resource" key="gateway-system/gateway-api-renew" error="Operation cannot be fulfilled on certificates.cert-manager.io \"gateway-api-renew\": the object has been modified; please apply your changes to the latest version and try again"
I0817 00:50:37.129826       1 conditions.go:263] Setting lastTransitionTime for CertificateRequest "gateway-api-renew-9vrrx" condition "Approved" to 2023-08-17 00:50:37.129800929 +0000 UTC m=+232702.108290858
I0817 00:50:37.166759       1 conditions.go:263] Setting lastTransitionTime for CertificateRequest "gateway-api-renew-9vrrx" condition "Ready" to 2023-08-17 00:50:37.166739523 +0000 UTC m=+232702.145229443
I0817 00:50:37.233277       1 controller.go:162] "cert-manager/certificates-readiness: re-queuing item due to optimistic locking on resource" key="gateway-system/gateway-api-renew" error="Operation cannot be fulfilled on certificates.cert-manager.io \"gateway-api-renew\": the object has been modified; please apply your changes to the latest version and try again"
I0817 00:50:37.258687       1 controller.go:162] "cert-manager/certificates-readiness: re-queuing item due to optimistic locking on resource" key="gateway-system/gateway-api-renew" error="Operation cannot be fulfilled on certificates.cert-manager.io \"gateway-api-renew\": the object has been modified; please apply your changes to the latest version and try again"
I0817 00:50:37.259986       1 controller.go:162] "cert-manager/certificates-key-manager: re-queuing item due to optimistic locking on resource" key="gateway-system/gateway-api-renew" error="Operation cannot be fulfilled on certificates.cert-manager.io \"gateway-api-renew\": the object has been modified; please apply your changes to the latest version and try again"
```
@rkosyk Do you know some solutions?
