### ISSUE TITLE
Dynamic header matching in HTTPRoute

### ISSUE THREAD

**Issue by frankbu** [kubernetes-sigs/gateway-api#2198]
**What would you like to be added**:
A standard API for routing based on matching metadata derived from dynamically evaluated request headers.

**Why this is needed**:
Users want to be able to route HTTP requests based on a validated JWT associated with the request. \
Istio, for example, supports this by using header names with a special prefix (`@`) in a httproute header match configuration, to indicate that the matching is not against a static header value, but rather the metadata associated with the validated JWT: https://istio.io/latest/docs/tasks/security/authentication/jwt-route/#configuring-ingress-routing-based-on-jwt-claims

Although Istio could support this in Gateway API routes with some implementation specific (e.g., prefix) solution, it would be better to define an optional standard API for this kind of routing in Gateway API.

Maybe simply allowing some prefix (e.g., `@`) in a header name to allow for  implementation-specific dynamic header matching would be minimally sufficient? Beyond that, defining some standard dynamic header names (like the one to use to match JWT metadata, for example) would also be nice to have in the Gateway spec.

**Comment by brianehlert** [comment]
This came up in a conversation between myself, @kflynn and @robscott a few weeks back and I have been slow at starting the write-up.
Looking across existing implementations (not all Gateway API of course) there are respectable differences that need to be surfaced.  
Not to mention there are the two use cases of validation and claims checking.
Let me see how quickly I can get my current (and not polished) write-up checked in for review and to start the broader process.

**Comment by pleshakov** [comment]
I wonder if combined with here https://github.com/kubernetes-sigs/gateway-api/issues/2166 , a generalized case here is implementation specific routing - data plane provides some parameters which can be used to make a routing decision.

Perhaps something like this could work:

Client IP based routing:
```yaml
  - matches:
      proxyKeys:
      - name: $client_ip # proxy specific
        type: CIDR # proxy specific
        value: 192.168.0.0
    backendRefs:
    - name: backend-local
      port: 80
```
JWT claim based routing:
```yaml
  - matches:
      proxyKeys:
      - name: $jwt_claim_group # proxy specific
        type: Exact # proxy specific
        value: group-1
    backendRefs:
    - name: backend-group1
      port: 80
```
Cookie based routing:
`````yaml
  - matches:
      proxyKeys:
      - name: $cookie_version # proxy specific
        type: Exact # proxy specific
        value: v2
    backendRefs:
    - name: backend-v2
      port: 80
```
