### ISSUE TITLE
Experimental conformance suite: Extended skipped tests not being reported

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/gateway-api#2206]
With a conformance suite config similar to the below:

```go
	cSuite, err := suite.NewExperimentalConformanceTestSuite(suite.ExperimentalConformanceOptions{
		Options: suite.Options{
                        ...
                        // Note this vs. using the EnableAllSupportedFeatures and ExemptFeatures field
			SupportedFeatures: suite.AllFeatures.Delete(suite.MeshCoreFeatures.UnsortedList()...),
			SkipTests: []string{
				tests.HTTPRouteRedirectPortAndScheme.ShortName,
			},
		},
		Implementation: conformance_v1alpha1.Implementation{
                         ...
		},
		ConformanceProfiles: sets.New(
			suite.HTTPConformanceProfileName,
			suite.TLSConformanceProfileName,
		),
	})
```

The resulting conformance report does not show any tests are skipped:

```yaml
        apiVersion: gateway.networking.k8s.io/v1alpha1
        date: "2023-07-19T20:34:17Z"
        gatewayAPIVersion: TODO
        implementation:
          contact:
          - '@projectcontour/maintainers'
          organization: projectcontour
          project: contour
          url: https://github.com/projectcontour/contour
          version: ""
        kind: ConformanceReport
        profiles:
        - core:
            result: success
            statistics:
              Failed: 0
              Passed: 10
              Skipped: 0
            summary: ""
          name: TLS
        - core:
            result: success
            statistics:
              Failed: 0
              Passed: 28
              Skipped: 0
            summary: ""
          extended:
            result: success
            statistics:
              Failed: 0
              Passed: 9
              Skipped: 0
            summary: ""
            supportedFeatures:
            - HTTPRouteQueryParamMatching
            - HTTPRouteSchemeRedirect
            - HTTPRouteHostRewrite
            - HTTPRoutePathRewrite
            - HTTPRouteRequestMirror
            - HTTPResponseHeaderModification
            - HTTPRoutePortRedirect
            - HTTPRoutePathRedirect
            - HTTPRouteMethodMatching
          name: HTTP
```
