### ISSUE TITLE
Need Clarification: In GRPCRoute, does the type of method match count for priority?

### ISSUE THREAD

**Issue by randmonkey** [kubernetes-sigs/gateway-api#2216]
In the specification of precedence of GRPCRoute rules here https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.GRPCRouteRule:
```
Precedence MUST be given to the rule with the largest number of:

  - Characters in a matching non-wildcard hostname.
  - Characters in a matching hostname.
  - Characters in a matching service.
  - Characters in a matching method.
  - Header matches.
```
The `Type` of method match is not mentioned here. I want to get a explanation about the priority of `Type` field in method match:
  - Does it count in precedence?
  - Should `Exact` method match take precedence over method match with other types?
  For example, if two rules like this

```yaml
matches:
- method:
    type: Exact
    service: v1
    method: foo
backendrefs:
- name: service1
  port: 80
```
and 
```yaml
matches:
- method:
    type: RegularExpression
    service: v1
    method: [a-z]+
backendrefs:
- name: service2
  port: 80
```

Which service will A GRPC request to `/v1/foo` go? According to the specification where there is no place for priority of `Type` of the match, the latter one will be matched and the request will go to service2. This seems weird when the non-exact match took the precedence over the exact match. So I need clarification here on the priority of `type` field in method match here. What is the intention on the priority of the fields in method match here?
