### ISSUE TITLE
Clarify ParentRef Uniqueness with Port and SectionName

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2326]
Currently the webhook and CEL validation consider the following valid:

```yaml
- name: "foo"
  sectionName: "bar"
- name: "foo"
  port: 80
```

I personally don't think these should be considered unique and instead we should only consider parentRefs unique if:

1. They both specify different section names
OR
2. They both specify different port numbers

Since the `port` field in `parentRef` is still experimental, we still have a window to tighten this validation if we want to. 

Thanks to @gauravkghildiyal for catching this in #2320!
