### ISSUE TITLE
Can I change the path before send to backend?

### ISSUE THREAD

**Issue by crazy-canux** [kubernetes-sigs/gateway-api#2344]
**What happened**:

`failed: error cause: no-error-isolation: Error GWCER104: HTTPRoute "shared/internal-http-route" is misconfigured, err: BackendRefs cannot be specified if "RequestRedirect" filter configured.`

**What you expected to happen**:

request send to "http://demo.gcp.com/nginx" will be rewrite.
only "/" will send to backend nginx service.

**How to reproduce it (as minimally and precisely as possible)**:

```
  hostnames:
  - "demo.gcp.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /nginx
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: nginx
      namespace: shared
      kind: Service
      port: 80
```

**Anything else we need to know?**:

How to implement this in gateway api.
