### ISSUE TITLE
Gateway no IP address

### ISSUE THREAD

**Issue by faresherhar** [kubernetes-sigs/gateway-api#2452]
### Issue

The GatewayClass is created with success `Ready: True`, and the same thing for the Gateway, but no IP address is generated for the Gateway. The httpRoute, it is created, but in the Gateway description, it shows `Attachments: 0`.

We've spent quite a time already troubleshooting, and still don't have any clue of the issue. 
Thanks for your help.

### Description

We're working on Argo Rollout, with HAProxy, and for that we're installing Gateway API.

As the [Documentation for HAProxy Kubernetes Ingress Controller 1.10 ](https://www.haproxy.com/documentation/kubernetes/latest/usage/gateway-api/install-gateway-api-components/) explains, we're using the [Experimental v0.0.5 of Gateway API](https://github.com/kubernetes-sigs/gateway-api/tree/v0.5.1), while following the [Gateway API v0.0.5 Examples](https://github.com/kubernetes-sigs/gateway-api/tree/v0.5.1/examples/experimental/v1alpha2).

> Environment

* Ubuntu 20.4, Kubernetes 1.22, HAProxy Controller Helm Chart 1.33.1 

> Gateway API Manifests

```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: haproxy-ingress-gatewayclass
spec:
  controllerName: haproxy.org/gateway-controller

---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: testapp
  namespace: testapp
spec:
  gatewayClassName: haproxy-ingress-gatewayclass
  listeners:
  - name: listener1
    protocol: TCP
    port: 8000
    allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute

---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: testapp
  namespace: testapp
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: testaapp
      namespace: testaapp
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: testapp
      port: 8080
```

> Application

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: testapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  namespace: testapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      imagePullSecrets:
        - name: XXXXX
      containers:
        - name: testapp
          image: XXXXX/testapp
          ports:
          - containerPort: 8080
          env:
            - name: TESTAPP_VERSION
              value: BLUE

---
apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: testapp
spec:
  selector:
    app: testapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
```
