### ISSUE TITLE
gateway api: migration to http route not working as expected

### ISSUE THREAD

**Issue by Rez0k** [kubernetes-sigs/gateway-api#2506]
Hi,

I am trying to migrate from virtual service to http route, 
I will try to describe the flow of my application, my route to my application is `app.example.com`
I am hosting my app on aws cloudfront, when accessing the app on any route except `/api` the user is forwarded to s3 and gets the static files, when the route prefix is `/api` the user is forwarded to aws ALB and then to istio with httproute.

diagram:
```
app.example.com -> cloudfront -> s3 -> static files
(not working anymore)
app.example.com/api/somerequest -> cloudfront -> alb -> gateway (gateway api) -> httproute -> backend service
(worked in past)
app.example.com/api/somerequest -> cloudfront -> alb -> gateway (istio gateway) -> virtualservice -> backend service
```

My problem is that the backend service can't get the request from the http route and I can't figure out why.
Everything is working fine with istio virtual service, but not with httproute and gateway api.
(if I expose another service that does not go from cloudfront like `admin.example.com` it works well).

istio config (works):
```
kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: external-gateway
  namespace: istio-ingress
spec:
  servers:
    - port:
        number: 443
        protocol: HTTPS
        name: https
      hosts:
        - '*'
      tls:
        mode: SIMPLE
        credentialName: tls-secret
  selector:
    istio: ingressgateway

---

kind: VirtualService
apiVersion: networking.istio.io/v1beta1
metadata:
  name: backend-service
  namespace: example
  labels:
    app: backend-service
spec:
  hosts:
    - app.example.com
  gateways:
    - istio-ingress/external-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: backend-service
            port:
              number: 80
```

gateway api config (not working)
```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: external-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - group: ''
            kind: Secret
            name: tls-secret
            namespace: istio-ingress
      allowedRoutes:
        namespaces:
          from: All

---

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: backend-service
  namespace: example
  labels:
    app: backend-service
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-ingress
      name: external-gateway
  hostnames:
    - app.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - group: ''
          kind: Service
          name: backend-service
          port: 80
          weight: 1
```

I know that I posed some istio config here, but you can ignore them.
Why gateway api does not get that the request that passed from cloudfront is `app.exmaple.com` and pass the request to the backend service?
