### ISSUE TITLE
GEP 713: merged inherited policy may cause unexpected result

### ISSUE THREAD

**Issue by spacewander** [kubernetes-sigs/gateway-api#2528]
Considering people have two inherited policies like this:

Gateway level:
```
spec:
   targetRef:
     ...  
     kind: Gateway
default:
     ext_auth:
         http_service:
             ...
```

HTTPRoute level:
```
spec:
   targetRef:
     ...  
     kind: HTTPRoute
default:
     ext_auth:
         grpc_service:
             ...
```

The merged result will be:
```
default:
     ext_auth:
         http_service:
            ...
         grpc_service:
             ...
```

If the `ext_auth` is defined to use either `http_service` or `grpc_service`, then merging between sane policies may cause an unexpected result.

If we change the definition of `ext_auth` to:
```
   kind: http / grpc
   http_service:
            ...
   grpc_service:
            ...
```

the problem will be solved.

It would be better to mention that people need to take care of their definition when defining inherited policy.
