### ISSUE TITLE
Docs: examples missing whitespace

### ISSUE THREAD

**Issue by therealmitchconnors** [kubernetes-sigs/gateway-api#2555]
Many or all of the examples on https://gateway-api.sigs.k8s.io/reference/spec/ are missing leading whitespace on every line.  For instance, the example under https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteRule appears as:
```
matches:
- path:
value: "/foo"
headers:
- name: "version"
value: "v2"
- path:
value: "/v2/foo"
```
but I think it's meant to be 
```
matches:
- path:
    value: "/foo"
  headers:
  - name: "version"
    value: "v2"
- path:
  value: "/v2/foo"
```
