### ISSUE TITLE
Invalid value for Address Type in Gateway resource

### ISSUE THREAD

**Issue by luigi-bitonti** [kubernetes-sigs/gateway-api#2632]
**What happened**: I have the following error: 

> failed to translate Gateway "gateway/test": Error GWCER106: Gateway "gateway/test" is invalid, err: unsupported address type "IPAddress", only "NamedAddress" is supported..

**What you expected to happen**: IPAddress type should be supported in apiVersion gateway.networking.k8s.io/v1beta1

**How to reproduce it (as minimally and precisely as possible)**: Apply this YAML:
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: test
  namespace: gateway
spec:
  gatewayClassName: gke-l7-rilb
  addresses:
  - type: IPAddress
    value: "10.100.100.2"
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: HTTPRoute
    tls:
      mode: Terminate
      certificateRefs:
      - name: default-cert-secret
```

**Anything else we need to know?**:
