### ISSUE TITLE
CertificateRefs should NOT be required when TLS mode is "Terminate"

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2668]
**What happened**:
CEL validation currently requires that CertificateRefs are specified when TLS mode is set to "Terminate":

https://github.com/kubernetes-sigs/gateway-api/blob/195d9882f816c9002eede96b2eda171ac454a6c1/apis/v1/gateway_types.go#L378

**What you expected to happen**:
This validation should be removed as implementations should be able to support other ways to configure TLS certificates. (One example would be [GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway#secure-using-ssl-certificate), but I don't think it is a secure practice to _require_ all TLS certificates to be configured within a cluster).

Thanks to @gauravkghildiyal for catching this one!

**Comment by robscott** [comment]
We discussed this issue at today's community meeting and there were some suggestions that `CertificateRefs` should be used for every reference to a TLS Certificate. In my opinion, that would not be a good practice. Let's consider the options implementations might consider when supporting references to certificates outside of Kubernetes:

## 1. Virtual Resource
With this approach, we use certificate references but just use a "virtual" (nonexistent) resource as a way to reference something outside of Kubernetes.
```yaml
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        group: certificates.example-vendor.com
        kind: TLSCertificate
        name: store-example-com
```

**Pros:**
* No additional resources needed
* Reuses certificateRefs field

**Cons:**
* Likely confusing that corresponding TLSCertificate resource does not exist
* Someone could install a TLSCertificate CRD to cause extra confusion
* Sometimes external resource names are not valid Kubernetes resource names so this would not work in all cases

## 2. Custom Resource
This is the same as above, but instead of a virtual resource, we're creating a new Custom Resource as well:
```yaml
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        group: certificates.example-vendor.com
        kind: TLSCertificate
        name: store-example-com
---
kind: TLSCertificate
apiVersion: certificates.example-vendor.com/v1
metadata:
  name: store-example-com
spec:
  certName: store-example-com
```

**Pros:**
* Certificate name can have different validation than a Kubernetes resource name so this can support more use cases

**Cons:**
* Unnecessarily verbose configuration
* More things that can break - the reference to the TLSCertificate can be invalid or the reference from the TLSCertificate can be invalid
* If multiple Gateways reference the same TLSCertificate Kubernetes resource, the blast radius of changes is awfully large (imagine if someone deleted a TLSCertificate resource that was used by multiple Gateways)
* If Gateways in different namespaces refer to the same certificate, you either need to involve ReferenceGrant to allow cross-namespace references or have duplicate TLSCertificate resources per namespace (note that cross-namespace references are not meaningful in this case because we're doing this to refer to resources outside of Kubernetes)

## 3. Custom TLS Option
Instead of using CertificateRefs, we can use a TLS option. Note that per the spec, "Options are a list of key/value pairs to enable extended TLS configuration for each implementation", so this feels like a reasonably appropriate use of the spec - referring to an implementation-specific concept.

```yaml
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        example-vendor.com/certificate-name: store-example-com
```

**Pros:**
* Most concise configuration available
* Avoids unnecessary intermediate resources
* Supports more extensive set of characters

**Cons:**
* Does not populate CertificateRefs
* Loosened CertificateRef validation could make it slightly harder to find configuration issues

In my opinion, this is the least bad option of them all. I think we very much need to support TLS Certificates that are defined outside of Kubernetes, and on today's call, I think there was broad agreement on that goal, so the real question is just "how". Although implementations can use any of the above approaches, I feel strongly that we should allow the third one with our validation.

As one final note, it's worth considering that some Gateways may rely on certificate generation where the Certificate is populated _after_ the Gateway is defined. Removing this validation would also support that use case.
