### ISSUE TITLE
Kubernetes Error When Referencing Service in Different Namespace Despite ReferenceGrant

### ISSUE THREAD

**Issue by donovan-shook** [kubernetes-sigs/gateway-api#2670]
**What happened**:
I am encountering an error when trying to reference a Kubernetes Service in a different namespace using an HTTPRoute, despite having a ReferenceGrant in place. The error occurs only when the Service is referenced from a different namespace. Referencing the same Service from the same namespace works without issues.

**Error Message:**
Error cause: reference-not-permitted: Error GWCER104: HTTPRoute "backbone-meta-green/backbone-meta-green-http-route" is misconfigured, err: cannot use backend backbone-meta-blue/httpbin, references to backends in other namespaces are not supported.

**What you expected to happen**:
I expect the HTTPRoute in cross-ns-2 to successfully reference the Service httpbin in cross-ns-1 with the ReferenceGrant in place.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy the Gateway, Service, and Deployment as per the provided manifests.
2. Apply the ReferenceGrant.
3. Deploy the HTTPRoute.
4. Observe the error.

**Anything else we need to know?**:
## Additional Context
Cloud Provider: Google Cloud Platform

## Assistance Required
I would appreciate any guidance or suggestions on resolving this issue, especially if there are additional configurations or steps I may have missed that allow for cross-namespace service references in this context.

## Manifest Configuration
Below is the manifest configuration I am using:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
    name: cross-ns-gateway
    namespace: gateway-infra
spec:
    addresses:
        - type: NamedAddress
          value: cross-ns-gateway-ip
    gatewayClassName: gke-l7-global-external-managed
    listeners:
        - allowedRoutes:
              namespaces:
                  from: All
          name: https
          port: 443
          protocol: HTTPS
          tls:
              mode: Terminate
              certificateRefs:
                  - name: gateway-cert-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: httpbin
    namespace: cross-ns-1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: httpbin
    template:
        metadata:
            labels:
                app: httpbin
        spec:
            containers:
                - name: httpbin
                  image: kennethreitz/httpbin
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: httpbin
    namespace: cross-ns-1
spec:
    selector:
        app: httpbin
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
    name: cross-ns-reference-grant
    namespace: cross-ns-1
spec:
    from:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          namespace: cross-ns-2
    to:
        - group: ''
          kind: Service
          name: httpbin
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
    name: cross-ns-http-route
    namespace: cross-ns-2
spec:
    hostnames:
        - cross-ns-test.com
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: cross-ns-gateway
          namespace: gateway-infra
    rules:
        - backendRefs:
              - group: ''
                kind: Service
                port: 8080
                name: httpbin
                namespace: cross-ns-2
          matches:
              - path:
                    type: PathPrefix
                    value: /
```
