### ISSUE TITLE
GEP: Support Matching Scheme in HTTPRouteMatch

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/gateway-api#2809]
The scheme match via pseudo headers suggested in https://github.com/kubernetes-sigs/gateway-api/issues/2455 only applies to HTTP/2. It would be useful to still match on the scheme for _any_ HTTP version.

One use case is the match could be used to prevent redirect loops. From https://github.com/kubernetes-sigs/gateway-api/issues/1185#issuecomment-1962181068

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-filter-redirect
spec:
  hostnames:
    - redirect.example
  rules:
    - matches:
      - scheme: http 
      filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
```

In the above example we have the HTTPRoute perform a redirect if the scheme of the request is `http`
