### ISSUE TITLE
Support DirectResponse HTTPRouteFilter

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#2826]
**What would you like to be added**:

A new HTTPRouteFilter that allows users to directly respond to requests with a specific body and status w/o sending it to a backend.

Existing implementations that have this feature
Istio - https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPDirectResponse
Contour https://projectcontour.io/docs/1.28/config/api/#projectcontour.io/v1.HTTPDirectResponsePolicy

**Why this is needed**:

* Adding a catch-all / fallback route to `HTTPRoute`

**Comment by howardjohn** [comment]
Obviously Istio has this as you noted, so I am in favor of this, but just want to note its a tricky tradeoff of how big we allow. Good for simple "return 404" but anything more complex becomes a bit dicey

**Comment by youngnick** [comment]
Yes, I think that anything we add will need to have a _strict_ limit about size. And an explanation that no, we really won't increase the limit.

**Comment by lianglli** [comment]
Why this is needed:

For example, some hosts want to disable crawl any of the website's pages. 
If the request path is "/robots.txt", the gateway will return  200 OK with body 
"User-agent: *
Disallow: /".

Based on the following HTTPRoute, the host "http.route.robots.com" with path "/robots.txt" will be disallowed always.

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route-cookie
spec:
  hostnames:
  - http.route.robots.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gateway
  rules:
  - backendRefs:
    - kind: Service 
       name: http-route-production
       port: 7001
    matches:
    - path:
         type: PathPrefix
         value: /
  - directResponse:
    - status: 200
       body: 
         string: "User-agent: *\nDisallow: /"
    matches:
    - path:
         type: Exact
         value: /robots.txt
```

**Comment by lianglli** [comment]
Why this is needed:

Moreover, if there is a L7 attack, the directResponse will return 404 based on a new HTTPRoute asap.

Then, the upstream service will be able to process the normal requests without any changes.

E.g., upstream service "http-route-production" add a HTTPRoute for protecting L7 attack for the host "http.route.com" with path "/acs":

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route-cookie
spec:
  hostnames:
  - http.route.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gateway
  rules:
  - backendRefs:
    - kind: Service 
       name: http-route-production
       port: 7001
    matches:
    - path:
         type: PathPrefix
         value: /
  - directResponse:
    - status: 404
    matches:
    - path:
         type: Exact
         value: /acs

**Comment by lianglli** [comment]
> Yes, I think that anything we add will need to have a _strict_ limit about size. And an explanation that no, we really won't increase the limit.

Yes, it is.
The directResponse is used to return a response with small body or no body. 

E.g.,
```yaml
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=128
	Value string `json:"value"`
```

**Comment by NissesSenap** [comment]
I also have a use-case for this.
I have an application with x number of paths, and I want all of them to be exposed to the internet except 1.

Today I can write a httpRoute with `rules.matches.path`to whitelist all paths I want to be available, but this becomes very boring if I have an app with a long list of paths. So instead of doing whitelist/allowlist, I would like to be able to do blacklist/blocklist.

For example:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gateway
  rules:
    - directResponse:
      - status: 404
      matches:
      - path:
           type: Exact
           value: /secretPath
    - backendRefs:
        - name: echo
          kind: Service
          port: 1027
```

**Comment by lianglli** [comment]
> I also have a use-case for this. I have an application with x number of paths, and I want all of them to be exposed to the internet except 1.
> 
> Today I can write a httpRoute with `rules.matches.path`to whitelist all paths I want to be available, but this becomes very boring if I have an app with a long list of paths. So instead of doing whitelist/allowlist, I would like to be able to do blacklist/blocklist.
> 
> For example:
> 
> ```yaml
> apiVersion: gateway.networking.k8s.io/v1
> kind: HTTPRoute
> metadata:
>   name: echo
> spec:
>   parentRefs:
>   - group: gateway.networking.k8s.io
>     kind: Gateway
>     name: http-gateway
>   rules:
>     - directResponse:
>       - status: 404
>       matches:
>       - path:
>            type: Exact
>            value: /secretPath
>     - backendRefs:
>         - name: echo
>           kind: Service
>           port: 1027
> ```

The directResponse of HTTPRouteFilter is able to fit your requirement.

I'm working on a GEP for directResponse that focuses on background and past implementations first.

**Comment by jbohanon** [comment]
@lianglli were you able to make any progress on a GEP for this feature?

**Comment by youngnick** [comment]
As for other Provisional GEPs, the critical parts are What this is, Why we need it, and Who it's for, along with what is currently supported in various data planes and/or implementations. Would love to see a Provisional GEP PR like that.

**Comment by lianglli** [comment]
Yes, get it.

**Comment by gganley** [comment]
Per suggestion by Mike Morris in the Istio slack I'd like to add my use case

Right now we're moving from VMs fronted by HAProxy to K8s using K8s G8way + Istio (plus other stuff). One of the hang ups I've encountered in trying to recreate our existing behavior is the lack `errorfile` directive in haproxy or `return` in nginx. This allows an inline of an error code and a body. To recreate this in the existing k8s gateway api I need to create a `null-backend` service whose only job is to act as the backend to `return 403 "<html><body><h1>\n403 Forbidden</h1>Request forbidden by administrative rules.\n</body></html>\n"`

```conf
frontend fe_https
    default_backend null
    # lots of acls either http-request deny or allowing to specific backends
    acl deny path_beg /edge/api/internal
    acl api_backend path_beg /edge/api
    http-request deny if deny
    use_backend api if api_backend

backend api
    server edge-api ...

backend null
    errorfile 403 /usr/local/etc/haproxy/403.http
```

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: translation
spec:
  parentRefs:
  - name: external
  rules:
  - matches: # deny
    - path:
        type: PathPrefix
        value: /edge/api/internal
    filters:
    - type: DirectResponse
      directResponse:
        statusCode: 403
        body:
          string: "Finger wag"
  - matches: # api
    - path:
        type: PathPrefix
        value: /edge/api
    backendRefs:
    - name: edge-api
      port: 8080
  - filters: # default_backend
    - type: DirectResponse
      directResponse:
        statusCode: 403
        body:
          string: "Finger wag"
  
```

**Comment by bravenut** [comment]
@gganley we have a very similar use case and I would also appreciate the direct response filter within HTTPRoutes CRs a lot. Instead of using a custom service that returns the custom responses, we're applying an Envoy filter custom resource to the gateway, where you can simply patch the route configuration to use the direct response, works like a charm, but it would be nice to accomplish this without additional overhead and just configure it in the HTTPRoute.

**Comment by arkodg** [comment]
Envoy Gateway [just added this a filter](https://gateway.envoyproxy.io/docs/api/extension_types/#httpdirectresponsefilter) in v1.2, here's an[ example](https://gateway.envoyproxy.io/docs/tasks/traffic/direct-response/)

**Comment by dudicoco** [comment]
Is there a workaround for this issue until it's implemented?

I've tried working around it by using `RequestRedirect` to reroute traffic to another path:
```yaml
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /metrics
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /metrics
        statusCode: 301
        scheme: https
```

This did not work, getting the following error when attempting to access the URL:
> 400 Bad Request
> The plain HTTP request was sent to HTTPS port

**Comment by gganley** [comment]
> Is there a workaround for this issue until it's implemented?
> 
> I've tried working around it by using `RequestRedirect` to reroute traffic to another path:
> 
>   rules:
>   - matches:
>     - path:
>         type: PathPrefix
>         value: /metrics
>     filters:
>     - type: RequestRedirect
>       requestRedirect:
>         path:
>           type: ReplaceFullPath
>           replaceFullPath: /metrics
>         statusCode: 301
>         scheme: https
> This did not work, getting the following error when attempting to access the URL:
> 
> > 400 Bad Request
> > The plain HTTP request was sent to HTTPS port

Are you looking to do https upgrade? I suspect the 400 is because your 301 didn’t have a Location header.

**Comment by cskinfill** [comment]
I'm also looking to support a related use-case.  In my case, I would like to implement a catch-all `HTTPRoute` that returns a `404` for any request, regardless of hostname, to the path `/metrics` handled by the Gateway.  The reason is to ensure that a service that exposes a `/metrics` endpoint doesn't accidentally leak that to public traffic.  Ideally, I would like to configure this `HTTPRoute` without the need for a backend that just returns a 404.  I'd like to have the Gateway itself just return a `404`.

**Comment by bazilmarkov** [comment]
Another use case for this feature is to emulate CORS behavior by sending a direct response to a pre-flight request, as [this feature ](https://gateway-api.sigs.k8s.io/geps/gep-1767/?h=cors)is still in progress.

**Comment by shaneutt** [comment]
I also tend to think this will be a helpful feature.

Seems in general we have enough consensus to consider this triaged.

/triage accepted

**Comment by JacobAmar** [comment]
I used envoyfilter for it on a gateway, and returning it via percentage of the traffic, by default, requests will be routed to the backend it looks like this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: test
  namespace: test-ns
spec:
  workloadSelector:
    labels:
      app: test-lb
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          portNumber: 80
      patch:
        operation: INSERT_BEFORE
        value:
          match:
            prefix: "/"
            runtime_fraction:
              default_value:
                numerator: 100 # we can change the percentage here
                denominator: HUNDRED
          direct_response:
            status: 200
            body:
              inline_string: 'this is a test'
          response_headers_to_add:
            - header:
                key: "test"
                value: "true"
              append: false
```
