### ISSUE TITLE
No validation of RegularExpression in HTTPRoute

### ISSUE THREAD

**Issue by qts0312** [kubernetes-sigs/gateway-api#2886]
**What happened**:
As [https://github.com/istio/istio/issues/49993](https://github.com/istio/istio/issues/49993), when I provide an illegal value in HTTPHeaderMatch, it is not rejected and results in that HTTPRoute takes no effect.

**What you expected to happen**:
Illegal value in HTTPHeaderMatch should be rejected.

**How to reproduce it (as minimally and precisely as possible)**:
Here is the configuration.
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr
spec:
  parentRefs:
  - name: back
    kind: Service
    group: ''
    port: 80
  rules:
  - matches:
    - headers:
      - name: host
        type: RegularExpression
        value: "*.example.com"
    backendRefs:
    - name: ratings
      port: 8080
```

**Anything else we need to know?**:
