### ISSUE TITLE
 How to achieve single hostname with BOTH https and http path

### ISSUE THREAD

**Issue by e33ivanyauwai** [kubernetes-sigs/gateway-api#2991]
**What would you like to be added**:
Documentation or example about confiuring single hostname with BOTH https and http path.
e.g. https://www.example.com/, http://www.example.com/foo

**Why this is needed**:

How to achieve single hostname with BOTH https and http path, e.g.:
"/" with https tcp443
"/plaintext" with http tcp80

Something like:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
spec:
  parentRefs:
  - name: gateway-all
    namespace: default
    sectionName: http
  hostnames:
  - "www.example.com"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-only
spec:
  parentRefs:
  - name: gateway-all
    namespace: default
    sectionName: https
  hostnames:
    - "www.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /plaintext
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: http
            port: 80
```

**Comment by robscott** [comment]
Hey @e33ivanyauwai, I think I'm having trouble understanding the redirects in your example. If you're attaching a Route exclusively to an HTTP listener, why would you need to redirect to 80 + HTTP?

**Comment by e33ivanyauwai** [comment]
Thanks for your reply @robscott, our case is that we have a public website with https://example.com, but we also have some API endpoints with http that was feed to a legacy system, we cannot change the code for the legacy system.

I used Nginx Ingress Controller with the below before (with annotation to bypass some path from https), now I migrate to Gateway but it seems I cannot find the documentation about this.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: project_name-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: project_name
          servicePort: 80
```

**Comment by Mayank77maruti** [comment]
Hi @e33ivanyauwai , 

I think the solution involves:
1. Using multiple HTTPRoute resources to handle HTTPS and HTTP traffic separately.
2. Leveraging Gateway listeners to differentiate traffic based on protocols (TCP/443 for HTTPS, TCP/80 for HTTP).
3. Defining path-specific routing rules and filters in the HTTPRoute resources.

Proposed implementation:-

1. Gateway Configuration: Define a Gateway with listeners for both HTTP and HTTPS.

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: my-gateway-class
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "www.example.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: example-cert
    - name: http
      protocol: HTTP
      port: 80
      hostname: "www.example.com"
```
2. HTTPS Routing: Create an HTTPRoute to handle HTTPS traffic for /.

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
      sectionName: https
  hostnames:
    - "www.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: https-backend-service
          port: 443
```

3. HTTP Routing: Create a separate HTTPRoute to handle HTTP traffic for /api.

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
      sectionName: http
  hostnames:
    - "www.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: http-backend-service
          port: 80
```

Additional Considerations:
TLS Termination: The tls section in the HTTPS listener configuration indicates that the Gateway will handle TLS termination. This means the Gateway will decrypt incoming HTTPS traffic before forwarding it to the backend service.
