### ISSUE TITLE
ProtocolType may not work as expected because of the case

### ISSUE THREAD

**Issue by spacewander** [kubernetes-sigs/gateway-api#3184]
**What happened**:

Provide a configuration like:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default
spec:
  gatewayClassName: istio
  listeners:
  - name: tcp
    port: 10001
    protocol: tcp
    allowedRoutes:
      kinds:
      - kind: TCPRoute
```

The result is that this resource is accepted (because "tcp" is valid protocol name), but doesn't treat it as TCP protocol (because it is not equal to TCPProtocolType constant).

**What you expected to happen**:

Either this resource is rejected (because the TCP protocol name is "TCP", no "tcp"), or handle it as TCP protocol.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

IMHO, we can either require the ProtocolType to be treated as case-insensitive, or require all Core protocols to be uppercase.
