### ISSUE TITLE
Header based session persistence cannot be configured without `AbsoluteTimeout`

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/gateway-api#3214]
**What happened**:

Header based session persistence cannot be configured without `AbsoluteTimeout`.

If you apply -

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-header-based-session-persistence
  namespace: gateway-conformance-infra
spec:
  parentRefs:
    - name: same-namespace
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: infra-backend-v1
          port: 8080
        - name: infra-backend-v2
          port: 8080
      sessionPersistence:
        sessionName: session-a
        type: Header
```

it hits the validation issue:

```shell
AbsoluteTimeout must be specified when cookie lifetimeType is Permanent
```

**What you expected to happen**:

Header based session persistence shouldn't have `CookieConfig`, and it should be allowed Header based session persistence not to have `AbsoluteTimeout`.

**How to reproduce it (as minimally and precisely as possible)**:

Just apply -

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-header-based-session-persistence
  namespace: gateway-conformance-infra
spec:
  parentRefs:
    - name: same-namespace
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: infra-backend-v1
          port: 8080
        - name: infra-backend-v2
          port: 8080
      sessionPersistence:
        sessionName: session-a
        type: Header
```

**Anything else we need to know?**:
