### ISSUE TITLE
`GRPCRoute` docs on matching rules are unclear

### ISSUE THREAD

**Issue by rauanmayemir** [kubernetes-sigs/gateway-api#3229]
There are no examples or docs on specifying only the service name in matching rules like so:
```
  rules:
    - matches:
        - method:
            service: package.name.version.Service
```

There is a matching rule example for when you match by service name _and_ header value, but nothing for arguably the most common use case of routing by only the service name.
