### ISSUE TITLE
Better clarify when Listeners are distinct

### ISSUE THREAD

**Issue by dawid-nowak** [kubernetes-sigs/gateway-api#3297]
**What would you like to be added**:
Stronger clarification is needed what should happen when two listners are configured as follows:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: some-gateway
spec:
  gatewayClassName: some-proxy
  listeners:
  - name: http-1080
    protocol: HTTP
    port: 1080
  - name: tcp-1890
    protocol: TCP
    port: 1080
```

**Why this is needed**:
In the above sample the listeners are distinct as per current documentation. The problem is that it is not clear what should applicaton do in such scenario when both HTTPRoute and TCPRoute are attached. Evaluate TCPRoute and skip HTTPRoute or only evaluate HTTPRoute.
