### ISSUE TITLE
Group is not optional in LocalObjectReference

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/gateway-api#3322]
LocalObjectReference group field is not marked optional. So, it can't be left unspecified or set to empty string.

In BackendTLSPolicy, we try to ref to a Secret and CRD fails validation check as group is ""

Previous conv in Slack: https://kubernetes.slack.com/archives/CR0H13KGA/p1725096986532939

![Screenshot 2024-08-31 at 2 35 20 AM](https://github.com/user-attachments/assets/b30b85b6-54f2-41c5-8872-33c72cc508e0)

**Comment by youngnick** [comment]
Thanks for opening this, this is a relatively simple change that just needs `+optional` added to the Group field.

/good-first-issue

**Comment by theBeginner86** [comment]
Hi @youngnick 
Please assign me this issue. I'd like to fix this.

**Comment by tamalsaha** [comment]
Though it is a simple change, it relaxes the constraints on an api already marked v1. Not sure that is halal with the maintainers? Should this struct be copied for the BackendTLSPolicy and only relaxed there or relaxed everywhere? @youngnick

**Comment by candita** [comment]
This is strange.  I didn't have any issue with this in my [PR](#3212) for testing BackendTLSPolicy.  `caCertificateRefs`  should look something like this.

```
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: "backendtlspolicy-test"
  validation:
    caCertificateRefs:
    - group: ""
      kind: Secret
      name: "backend-tls-checks-certificate"
```
