### ISSUE TITLE
GEP: Circuit breaking

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#3358]
**What would you like to be added**:
Gateway API should support some method of configuring circuit breaking settings. This could be a Policy, a filter, or some other method.

Note that this is useful for both north-south (ingress) and east-west (GAMMA) use cases, so will need both groups to be on board with the approach.

**Comment by wpbeckwith** [comment]
As GEP-1731 for Configurable Retries in HTTPRoute is targeting the v1.5 release, IMHO Retries and Circuit Breaking are two sides of the same resilience coin in a distributed system, and providing a cohesive API for both would offer a significantly more complete and safer user experience in v1.5.

An upstream service failure will simply be amplified by an aggressive retry policy, leading to a retry storm that can permanently overwhelm the failing service or even induce cascading failures across the entire system. Circuit breaking is the only native mechanism to prevent this.

**Comment by allright** [comment]
Hi @youngnick, @wpbeckwith

I'd like to help move this GEP forward with a concrete API proposal.

## Current XBackendTrafficPolicy Structure

Looking at the current spec (experimental since v1.3.0), the structure is:

```yaml
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XBackendTrafficPolicy
spec:
  targetRefs: [...]           # REQUIRED (min: 1, max: 16)
  retryConstraint: {...}      # optional
  sessionPersistence: {...}   # optional
```

Only `targetRefs` is required. Both `retryConstraint` and `sessionPersistence` are optional fields that can be omitted entirely.

## Proposal: Add `circuitBreaker` as Optional Field

Following the same pattern, `circuitBreaker` would be another optional field at the same level:

```yaml
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XBackendTrafficPolicy
metadata:
  name: high-connection-limit
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: websocket-service

  # Existing optional fields
  retryConstraint:
    budget:
      percent: 20

  # NEW: Circuit Breaker (optional)
  circuitBreaker:
    thresholds:
      - priority: Default
        maxConnections: 1024
        maxPendingRequests: 1024
        maxRequests: 1024
        maxRetries: 3
      - priority: High
        maxConnections: 4096
        maxPendingRequests: 4096
        maxRequests: 4096
        maxRetries: 10
```

## Proposed API Spec

```go
// CircuitBreaker defines connection limits for a backend to prevent overload.
type CircuitBreaker struct {
    // Thresholds defines circuit breaker thresholds per priority level.
    // +optional
    Thresholds []CircuitBreakerThreshold `json:"thresholds,omitempty"`
}

// CircuitBreakerPriority indicates the priority level for circuit breaker thresholds.
// +kubebuilder:validation:Enum=Default;High
type CircuitBreakerPriority string

const (
    CircuitBreakerPriorityDefault CircuitBreakerPriority = "Default"
    CircuitBreakerPriorityHigh    CircuitBreakerPriority = "High"
)

// CircuitBreakerThreshold defines limits for a specific priority level.
type CircuitBreakerThreshold struct {
    // Priority specifies the priority level for these thresholds.
    // Default: "Default"
    // +optional
    Priority CircuitBreakerPriority `json:"priority,omitempty"`

    // MaxConnections is the maximum number of connections to the backend.
    // +optional
    MaxConnections *uint32 `json:"maxConnections,omitempty"`

    // MaxPendingRequests is the maximum number of pending requests allowed.
    // +optional
    MaxPendingRequests *uint32 `json:"maxPendingRequests,omitempty"`

    // MaxRequests is the maximum number of parallel requests.
    // +optional
    MaxRequests *uint32 `json:"maxRequests,omitempty"`

    // MaxRetries is the maximum number of parallel retries.
    // +optional
    MaxRetries *uint32 `json:"maxRetries,omitempty"`
}
```

## Why This Fits XBackendTrafficPolicy

| Aspect | Rationale |
|--------|-----------|
| **Same target** | Circuit breakers apply to backends (Services), same as retryConstraint |
| **Complements retryConstraint** | As @wpbeckwith noted, circuit breaking prevents retry storms caused by aggressive retry policies |
| **Consistent pattern** | Optional field, same level as existing fields |
| **No new CRD** | Extends existing resource |
| **Priority support** | Allows different limits for default vs high-priority traffic |

## Relationship with retryConstraint

These two features work together:

- **retryConstraint** — limits retry *rate* (percentage-based budget)
- **circuitBreaker** — limits concurrent *connections/requests* (absolute limits per priority)

Without circuit breakers, even a well-configured retry budget can overwhelm a backend if the base request volume is high enough.

## Questions

1. Does this field structure align with your vision for GEP #3358?
2. Should we add additional fields like `connectTimeout` or `outlierDetection`, or keep it minimal for v1?
3. What conformance level would be appropriate? (Extended seems fitting given retryConstraint is Extended)

cc @robscott @mikemorris ([GEP-1731](https://github.com/kubernetes-sigs/gateway-api/issues/1731) retries - related work)
