### ISSUE TITLE
Rename Matches to Match

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#355]
**What would you like to be added**:
I would like to rename field `matches` to `match`.

**Why is this needed**:
It reads better and other examples in the APIs where a singular field name is used for a list.

__Current__
```
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-app-1
  namespace: default
  labels:
    app: foo
spec:
  hostnames:
  - "foo.com"
  rules:
  - matches:
    - path:
        type: Prefix
        value: /bar
    forwardTo:
    - serviceName: my-service1
  - matches:
    - headers:
        type: Exact
        values:
          x-forwarded-proto: https
          magic: foo
      path:
        type: Prefix
        value: /some/thing
    forwardTo:
    - serviceName: my-service2
```

__Proposed:__
```
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-app-1
  namespace: default
  labels:
    app: foo
spec:
  hostnames:
  - "foo.com"
  rules:
  - match:
    - path:
        type: Prefix
        value: /bar
    forwardTo:
    - serviceName: my-service1
  - match:
    - headers:
        type: Exact
        values:
          x-forwarded-proto: https
          magic: foo
      path:
        type: Prefix
        value: /some/thing
    forwardTo:
    - serviceName: my-service2
```
