### ISSUE TITLE
Error "HTTPRoute in version "v1" cannot be handled as a HTTPRoute" when I try to apply an httproute with retry

### ISSUE THREAD

**Issue by Stephani0106** [kubernetes-sigs/gateway-api#3562]
Hello everyone!

I'm facing some problems using HTTP Route with retry in my cluster, we currently use Istio manifests to control our entire service mesh (virtual service) and we are migrating these manifests to the Gateway API, requiring translating the Istio Virtual Service to HTTP Route.

Below is an example of a current implementation with Istio Virtual Service and its equivalent in HTTP Route:

```yaml
# Istio - Virtual Service

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx-ingress
  namespace: apps
spec:
  hosts:
    - "ingress-lab.my-domain.com"
  gateways:
    - istio-ingress/ingressgateway
  http:
    - match:
        - uri:
            prefix: "/apps/nginx/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: nginx.apps.svc.cluster.local
            port:
              number: 80
      retries:
        attempts: 4
        perTryTimeout: 5s
        retryOn: gateway-error,connect-failure,refused-stream
```

```yaml
# Gateway API - HTTP Route

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-ingress
  namespace: apps
spec:
  parentRefs:
    - name: ingressgateway
      namespace: istio-ingress
  hostnames:
    - ingress-lab.my-domain.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /apps/nginx/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /
      backendRefs:
        - name: nginx
          namespace: apps
          port: 80
      retry:
        codes: [ 502, 503, 504 ]
        attempts: 4
        backoff: 5s
```

However, when I try to apply HTTP Route on my cluster, I get the following error:

```bash
$ kubectl apply -f http-route-ingress.yaml 

Error from server (BadRequest): error when creating "http-route-ingress.yaml": HTTPRoute in version "v1" cannot be handled as a HTTPRoute: strict decoding error: unknown field "spec.rules[0].retry"
```

If I remove the spec.rules.retry field, the error disappears:

```bash
$ kubectl apply -f http-route-ingress.yaml 

httproute.gateway.networking.k8s.io/nginx-ingress created
```

I saw in the API gateway documentation that the implementation of HTTPRoute retries is still on an experimental basis (https://gateway-api.sigs.k8s.io/geps/gep-1731). But in the API Gateway v1.2 documentation, this experimental functionality appears as supported in the v1 API version (https://kubernetes.io/blog/2024/11/21/gateway-api-v1-2/#httproute-retry-support).

I also tried to apply [this official example from the Kubernetes documentation](https://kubernetes.io/blog/2024/11/21/gateway-api-v1-2/#httproute-retry-support) and I get the same error of `HTTPRoute in version "v1" cannot be handled as a HTTPRoute`.

Can anyone tell me if there is something wrong with my implementation?
