### ISSUE TITLE
Allowed values for Path Prefix Rewrite

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/gateway-api#3593]
Currently we don't validate values in [ReplacePathPrefix](https://github.com/kubernetes-sigs/gateway-api/blob/5dd3155c9069144bc7c79e413ac92ac4dae14251/apis/v1/httproute_types.go#L1121). 

Users can have the following config:

```yaml
...
    matches:
    - path:
        type: PathPrefix
        value: /foo
    filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: bar (NOTE the absence of a leading "/")
              type: ReplacePrefixMatch
```

This will essentially screw the request, (tested with istio, i got 400). 

The question is what are our expectations around it and whether we should add CEL to the spec to disallow it. 

Technically, for a URI, it is possible to have something like `one.exmaple.com#<some-fragment>` or `one.exmaple.com?<query-params>` without a "/" in between, but AFAICT, most browsers normalize that and add a "/" in between, AND, more importantly, this feature is **path** rewrite and not a rewrite for other parts of the URI.

Thoughts?

/cc @mikemorris @arkodg @robscott @howardjohn @kflynn
