### ISSUE TITLE
HTTPRouteFilterType missing CORS, making it impossible to use

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#3649]
Currently we have: `RequestHeaderModifier;ResponseHeaderModifier;RequestMirror;RequestRedirect;URLRewrite;ExtensionRef`

We will need to add one for CORs so it can be used

**Comment by BeyondEvil** [comment]
Is there a workaround one can use today?

I was trying:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
spec:
  parentRefs:
    - name: istio-gateway
      namespace: istio-ingress
      sectionName: https
  hostnames:
    - 'argocd.k8s.company.com'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 80
    - filters:
        - type: CORS
          cors:
            allowOrigins:
              - '*'
            allowMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowHeaders:
              - '*'
            maxAge: 7200
```

and got `decoding error: unknown field "spec.rules[1].filters[0].cors"` which led me here.

**Comment by youngnick** [comment]
#3668 will fix this, but you should note that this feature will be available in Gateway API v1.3, which is not released yet.

**Comment by BeyondEvil** [comment]
Here's how I solved it for Istio for the time being (glad if it helps someone else who stumbles in here):

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cors-filter
  namespace: istio-ingress
spec:
  workloadSelector:
    labels:
      gateway.networking.k8s.io/gateway-name: istio-gateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.cors:
              '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
              allow_origin_string_match:
                - exact: '*'
              allow_methods: 'GET,POST,OPTIONS,PUT,DELETE'
              allow_headers: 'Content-Type,Authorization,Origin,Referer'
              expose_headers: 'X-Request-ID'
              max_age: '86400s'
              allow_credentials: true
```
