### ISSUE TITLE
gRPC reflection does not work as documented

### ISSUE THREAD

**Issue by muhammad-asn** [kubernetes-sigs/gateway-api#3805]
**What happened**:
When testing gRPC reflection with [grpcurl](https://github.com/fullstorydev/grpcurl), it appears that the "rules" must first be associated with an HTTPRoute before using a GRPCRoute.

**What you expected to happen**:
I think there's something No need to register the grpc port in `HTTPRoute`

**How to reproduce it (as minimally and precisely as possible)**:

### Install Gateway API
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: service-gateway
  namespace: istio-ingress
  labels:
    team: sre
spec:
  gatewayClassName: istio
  addresses:
  - value: private-nlb-ingressgateway.istio-ingress.svc.cluster.local
    type: Hostname
  listeners:
    - name: grpc-tls
      hostname: "*.staging.localhost.com"
      port: 20443
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: grpc
      hostname: "*.staging.localhost.com"
      port: 20010
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: http2
      hostname: "*.staging.localhost.com"
      port: 443
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      hostname: "*.staging.localhost.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
```

### First try (NOT WORKS)
1. Apply only `GRPCRoute`.
  ```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: backend-xyz
  namespace: app
  labels:
    name: backend-xyz
    env: staging
    namespace: app
spec:
  parentRefs:
  - name: service-gateway
    namespace: istio-ingress
    sectionName: grpc
  hostnames:
  - test.staging.localhost.com
  rules:
    - matches:
      # If no matches are specified, the default is to match every gRPC request.
      - method:
          service: grpc.reflection.v1.ServerReflection
      backendRefs:
        - name: backend-xyz
          namespace: app
          port: 20010
   ```

2. Run command.
```sh
$ grpcurl -plaintext test.localhost.com:20010 list
Failed to list services: server does not support the reflection API
```

### Second try (WORKS)
1. Apply `GRPCRoute`.
  ```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: backend-xyz
  namespace: app
  labels:
    name: backend-xyz
    env: staging
    namespace: app
spec:
  parentRefs:
  - name: service-gateway
    namespace: istio-ingress
    sectionName: grpc
  hostnames:
  - test.staging.localhost.com
  rules:
    - matches:
      # If no matches are specified, the default is to match every gRPC request.
      - method:
          service: grpc.reflection.v1.ServerReflection
      backendRefs:
        - name: backend-xyz
          namespace: app
          port: 20010
   ```

2. Apply HTTPRoute
```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-xyz
  namespace: app
  labels:
    name: backend-xyz
    env: staging
    namespace: app
spec:
  parentRefs:
  - name: service-gateway
    namespace: istio-ingress
    sectionName: http
  - name: service-gateway
    namespace: istio-ingress
    sectionName: grpc
  hostnames:
  - test.localhost.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 10s
      backendRefs:
        - name: backend-xyz
          namespace: app
          port: 20010
```

3. Run command
```sh
$ grpcurl -plaintext test.localhost.com:20010 list
Failed to list services: server does not support the reflection API
```

**Anything else we need to know?**:
- Istio version: `v1.25.0`
- Gateway API version: `v1.2.0`
