### ISSUE TITLE
CORS-should perfligh "OPTIONS" method be implicitly included in the matching rules if CORS filter is specified?

### ISSUE THREAD

**Issue by zhaohuabing** [kubernetes-sigs/gateway-api#3857]
When both a CORS filter and method matching are specified, the HTTPRoute must include the OPTIONS method for the CORS filter to function properly. Otherwise, preflight OPTIONS requests won’t match the route, and the CORS filter won’t be invoked.

For example:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cors-1
spec:
  parentRefs:
  - name: same-namespace
  rules:
  - filters:
    - type: CORS
      cors:
        allowOrigins:
        - "https://www.foo.com"
        allowMethods:
        - GET
        - OPTIONS
    matches:
    - path:
        type: PathPrefix
        value: /cors-1
      method: "GET"
    backendRefs:
    - name: infra-backend-v1
      port: 8080
```

Should we mention in the CORS filter API docs that the implementation should implicitly include the preflight OPTIONS method in the matching rules when a CORS filter is present on an HTTPRoute?

preflight requests: the request that contains both the `Access-Control-Request-Method` and `Origin` headers.

Update: as @howardjohn suggested in this [comment](https://github.com/kubernetes-sigs/gateway-api/issues/3857#issuecomment-2970794409), only allow preflight request as not every `OPTIONS` requests are CORS preflight.

Reference: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
> It is an OPTIONS request, using two or three HTTP request headers: Access-Control-Request-Method, Origin, and optionally Access-Control-Request-Headers.

**Comment by youngnick** [comment]
Sounds like a good idea to me. PRs welcomed.

**Comment by howardjohn** [comment]
Simply allowing OPTIONS is wrong and a violation of the users intent.

~Every CORS implementation handles **some** OPTIONS requests but not others -- only things that are 'preflight'.
What is "preflight" varies between implementations and is under-specified even in the GEP.

But pretty much everything is going to say, at minimum, a request must have Origin to be handled by the CORS and otherwise is going to passthrough.

So now by adding the CORS filter, if we implicitly allow OPTIONS, anyone can now send OPTIONS requests directly through the backend bypassing the CORS filter.

**Comment by howardjohn** [comment]
If we want to have specific handling of preflight connections then maybe this is acceptable. That is, an OPTIONS request will either be either...:
* Directly returned `200` with CORS headers
* Directly returned 404

Given the above HTTPRoute, and request hitting the backend that is not a GET **must** not be valid.

**Comment by zhaohuabing** [comment]
Currently, Envoy Gateway [returns 404 for preflight requests without `OPTIONS` method matching](https://github.com/envoyproxy/gateway/issues/6316).

I think we should either:
* implicitly allows  preflight requests(with both the `origin` and `access-control-request-method` headers) for any HTTPRoute with a CORS filter by adding a match for it, like:
  ```
  routes:
  - match:
      path: "/hello"
      headers:
        - name: ":method"
          exact_match: "OPTIONS"
        - name: origin
        - name: access-control-request-method
  ```

* surface a configuration error in the HTTPRoute status to let users know that `OPTIONS` isn’t allowed and will cause CORS issues

**Comment by howardjohn** [comment]
Yeah I definitely do not think an envoy limitations should lead us to permanently have an API that violates the users configuration in a manner that is potentially unsafe and exposed things they didn't expose. So to me we either need that to change in envoy (and analyze other implementations!) or keep it as a status thing?

**Comment by zhaohuabing** [comment]
It doesn't look like an Envoy limitation to me — it seems more like a semantic ambiguity in the Gateway API specification. Specifically, it’s unclear whether a CORS preflight request should be allowed when an HTTPRoute with a CORS filter matches specific methods but doesn’t explicitly include OPTIONS.

**Comment by howardjohn** [comment]
I mean that Envoy cannot do https://github.com/kubernetes-sigs/gateway-api/issues/3857#issuecomment-2970797616 AFAIK.

Note OPTION != Preflight, OPTION is a superset of preflight requests.

**Comment by zhaohuabing** [comment]
@howardjohn Thanks for the explanation. Would it make sense to implictly add a match with `OPTIONS` method  and `origin` and `access-control-request-method` headers when the CORS filter is present? 

According to https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request, a prefilght request is an OPTIONS request using these two headers.

> It is an OPTIONS request, using two or three HTTP request headers: Access-Control-Request-Method, Origin, and optionally Access-Control-Request-Headers.

```
routes:
- match:
    path: "/hello"
    headers:
      - name: ":method"
        exact_match: "OPTIONS"
      - name: origin
      - name: access-control-request-method
```

**Comment by howardjohn** [comment]
Yes, a preflight request is that. But that doesn't mean all requests with those properties are a preflight request. Square vs rectangle.

At the very least, Envoy does not currently treat it that way and will only prevent forwarding **matching** origin.

My guideline is this: if we are implicitly adding matches, they MUST not be forwarded to the backend. What the spec says is a "preflight" or not is not actually directly relevant to that, what matters is what an implementation will directly handle

**Comment by zhaohuabing** [comment]
Agree, if it's forwarded to the backend, then it's against user's origin intention.

**Comment by zhaohuabing** [comment]
> At the very least, Envoy does not currently treat it that way and will only prevent forwarding matching origin.

Envoy CORS filter won't forward preflights when `forward_not_matching_preflights` is set to true.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/cors/v3/cors.proto#extensions-filters-http-cors-v3-corspolicy

**Comment by howardjohn** [comment]
I am aware of envoys behavior. Not all Options requests are "preflight" so that flag does not make it safe to allow OPTION

**Comment by zhaohuabing** [comment]
We can just implicitly allow "preflight" requests:

```yaml
routes:
- match:
    path: "/hello"
    headers:
      - name: ":method"
        exact_match: "OPTIONS"
      - name: origin
      - name: access-control-request-method
```
