### ISSUE TITLE
GEP: Add pod selector to Gateway API policy attachment as top level field same as TargetRefs

### ISSUE THREAD

**Issue by aryan16** [kubernetes-sigs/gateway-api#3893]
Many of our new mesh workload APIs will require a mechanism to select specific pods as their target. While Kubernetes inherently supports selectors within a Spec as a top-level field, a consistent and clear approach is needed across our mesh APIs. Should we add a field called podLabelSelector in the Spec of the APIs as a general approach for the all the APIs that requires selectors as targets?

The APIs that can benefit from this - 
1. AuthorizationPolicy
2. AuthenticationPolicies

It is a new idea of proposing addition of label selector in the APIs for mesh whenever required.

Example - 

```
apiVersion: policies.controller.io/v1
kind: ColorPolicy
metadata:
  name: my-color-policy
spec:
   podLabelSelector: ## pod label selector
      matchLabels:
         env: production
```

We can add restrictions like to not use TargetRefs when selectors are used that way users can define policies just for the mesh.
