### ISSUE TITLE
Define standard conformance format for a GatewayClass to communicate what it supports to operators

### ISSUE THREAD

**Issue by mark-church** [kubernetes-sigs/gateway-api#482]
**What would you like to be added**:
GatewayClasses encapsulate the capabilities that an implementation of Service APIs supports. However, for the platform operators or application operators who might deploy Gateways in a cluster may not know exactly what within the API a given GatewayClass supports. This issue proposes a standard way for all GatewayClasses to communicate to a user what it supports.

Let's say I have an `acme-lb` GatewayClass. The GatewayClass should be able to tell me the following:

```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: supported
spec:
  gatewayClassName: supported
  listeners:  
  - protocol: 
      http: supported
      tcp: unsupported
      udp: unsupported
    port: supported
    routes:
      kind: 
        HTTPRoute: supported
        TCPRoute: unsupported
        UDPRoute: unsupported
      selector:
        matchLabels: supported
...
---
HTTPRoute:
  spec:
    hostnames: supported
    rules:
    - matches:
      - path:
          type: 
            prefix: supported
            exact: supported
            regularexpression: unsupported
            implementationspecific: unsupported
        headers:
          type:
            exact: supported
            implementationspecific: 
              contains: supported # Will match traffic with any single header that contains this string
              doesnotcontain: supported # Will match traffic if no headers contain this string 
...
```

This is a terrible example of the format but you get the idea :) Perhaps OpenAPI has some kind of capability for this.

The goals this aims to achieve:

- Provide a standardized way for all GatewayClasses to communicate which aspects of the API they support.
- Core fields must be supported to achieve conformance, but since extended fields can be optional it will be very useful to understand which extended fields are implemented by a given GatewayClass.
- Custom fields (like annotations, ImplementationSpecific fields, or CRDs that can be referenced) should also be able to be communicated in some way so operators can understand how a GatewayClass has been extended with additional functionality.
- Provide a way for the provider to give additional context to describe implementation-specific aspects of a core, extended, or custom field. The example above with `contains` illustrates this.

How a GatewayClass provider communicates to the operator what its capabilities are can be done in many different ways:
- Perhaps conformance tests spits this out as a standardized output and providers can simply put this in their docs
- Perhaps comments or fields within a GatewayClass implementation can fill out these fields. This would give the opportunity for implementors to add special comments and context regarding support for specific fields. This might be the case where a field is supported but how it functions requires more context or explanation. 

cc @robscott
