### ISSUE TITLE
Route selector improvements on Gateway

### ISSUE THREAD

**Issue by mark-church** [kubernetes-sigs/gateway-api#515]
**What would you like to be added**:
This issue has some proposals to improve Route selection and binding UX. The Route selection mechanisms on Gateway listeners look something like this:

```
kind: Gateway
...
spec:
  listeners:  
  - routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          gateway: prod-web-gw 
      namespaces:
        from: All
```
I wanted to record some feedback from some internal testers for Gateway in GKE:

- The default Route selection feels a little bit too permissive because the default settings will select all Routes within the Namespace if the Route owners do nothing (as in add no labels to their Routes). This can lead to the overexposure of Routes amongst Gateways.
- The selection mechanisms differ from Services and Pod label selection which also makes it a bit confusing and unintuitive. 

I wanted to propose some improvements to how Route selection works that might address these issues:
- Make `routes.selector` a required field
- An empty selector selects no Routes and similarly a Route with no labels will not bind with any Gateways
