### ISSUE TITLE
Add forwarding shortcut to Gateway Listener

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#529]
This is a follow up from what we discussed at today's community meeting. During that meeting, option B was favored due to its simplicity and clear purpose. This issue is closely related to https://github.com/kubernetes-sigs/service-apis/issues/174, but takes a slightly different approach.

---

Adding a forwarding shortcut to Gateway listeners would allow users to create simple Gateways without the need for Routes. This would be especially useful for L4 Gateways where TCP or UDP Routes provide rather minimal value. 

In all cases, we do not want to recreate advanced routing behavior at this level. This forwarding shortcut will not include weighting, delegation to additional routes, or traffic splitting. It is meant for the simplest of use cases. Anything beyond that should make use of route resources.

**Option A: DefaultBackend with Ingress-like behavior**
In addition to the L4 shortcut use case, this could also serve a similar purpose to the default backend that is part of the Ingress API. This could be used if no matching routes were found.

```yaml
listeners:
  - protocol: "TCP"
    port: 80
    defaultBackend:
      serviceName: "example"
      port: 8080
```

**Option B: BackendRef with exclusive behavior**
Alternatively, this field could be mutually exclusive with a route selector. When a backendRef was specified, the route selector would be ignored. This would dramatically simplify config for simple load balancers, most commonly L4 protocols.

```yaml
listeners:
  - protocol: "TCP"
    port: 80
    backendRef:
      serviceName: "example"
      port: 8080
```

**Protocol**
The upstream protocol would be determined by the app protocol or protocol defined by the backend, or if not specified at that level, the protocol defined by the listener.

Listener Protocol | Backend Port Protocol | Backend App Protocol | Selected Protocol
-- | -- | -- | --
HTTPS | HTTP |   | HTTP
HTTPS | HTTP | acme.io/custom | acme.io/custom
HTTP | HTTPS |   | HTTPS
TCP | HTTP |   | HTTP
TCP |   |   | TCP

**Comment by robscott** [comment]
There's also some related discussion around this in the [associated doc](https://docs.google.com/document/d/14vP98BavhFiIUZ198RtNjRGH1D5koIeRUsHb3jlMWAA/edit).

**Comment by hbagdi** [comment]
I saw this issue after reviewing this same content in Google doc: https://docs.google.com/document/d/14vP98BavhFiIUZ198RtNjRGH1D5koIeRUsHb3jlMWAA

**Comment by stevesloka** [comment]
Should we make the `backendRef` a set so you could configure multiple backends for the listener? 

e.g.:
```
listeners:
  - protocol: "TCP"
    port: 80
    backendRefs:
      - serviceName: "example"
         port: 8080
```
