### ISSUE TITLE
TLSRoute SNI match inconsistency

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#566]
TLS route:
```yaml
spec:
  rules:
  - matches:
    - snis: ["foo.com"]
    forwardTo:
    - serviceName: httpbin
      port: 443
```

HTTP route:
```yaml
spec:
  hostnames: ["foo.com"]
  rules:
  - forwardTo:
    - serviceName: httpbin
      port: 80
```

The inconsistency here feels a bit odd when compared to HTTPRoute.

Would it make sense to make a `hostnames` field in TLSRoute and remove the `snis` field in matches? Then the specs above would be identical (both looking like the "HTTP Route")
