### ISSUE TITLE
Extend route's gateway selection

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#568]
Currently, routes can select gateways by list or namespace or all. One thing that is missing is selecting based on class. This can be important when using extensions that are only supported by one class. For example, if I use the `nginx` class and depend on nginx-auth extension, I need to fail-closed - if I am selected by the `haproxy` class and auth is ignored we are in trouble.

One possible idea is to just add a new type of `From`:
```yaml
gateways:
  allow: FromClass
  gatewayClasses: [nginx]
```

However, now we are limited - we cannot specify specific Gateways *and* the class.

A more flexible idea would be to change FromList from explicit reference to "matchers", and add a class field. Basically, all three of the fields must match the gateway to select, and unset ones are ignored. If name is set namespace must be as well, since cross-namespace name selectors don't make sense

```yaml
gateways:
  allow: FromList
  gatewayRefs:
  - name: istio-ingressgateway
    namespace: istio-system # required if name is set
  - class: mesh # select any gateway with class=mesh
  - class: gke-xlb # select any gateway with class=gke-xlb if its in gke-system
    namespace: gke-system
  - namespace: my-gateway-namespace # select any gateway from my-gateway-namespace
  - name: istio-local
    namespace: istio-system
    class: istio # select a specific gateway, and enforce its a part of a specific class
```
