### ISSUE TITLE
Are multiple HTTPRoutes for one hostname with weight configuration supported?

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#573]
**What happened**:

- When multiple HTTPRoutes for the same hostname were defined, the weight will not work.

**How to reproduce it (as minimally and precisely as possible)**:

- Create multipe HTTPRoutes for the same hostname with `weight` field like this:

```
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-trafficsplit-1
spec:
  hostnames:
  - "my.trafficsplit.com"  # Same value with http-trafficsplit-2
  rules:
  - matches:
    forwardTo:
    - serviceName: my-trafficsplit-svc1
      port: 8080
      weight: 3
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-trafficsplit-2
spec:
  hostnames:
  - "my.trafficsplit.com"  # Same value with http-trafficsplit-1
  rules:
  - matches:
    forwardTo:
    - serviceName: my-trafficsplit-svc2
      port: 8080
      weight: 7
```

- This HTTPRoutes expects the traffic of 30% for my-trafficsplit-svc1 and 70% for my-trafficsplit-svc2.  But I think it is difficult to implement it by ingress providers because they need to recalculate the weight of the previous HTTPRoute whenever new HTTPRoute is created.

**Anything else we need to know?**:

- It would be easy to implment it for one HTTPRoute like below.

```
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-trafficsplit-1
spec:
  hostnames:
  - "my.trafficsplit.com"
  rules:
  - matches:
    forwardTo:
    - serviceName: my-trafficsplit-svc1
      port: 8080
      weight: 3
    - serviceName: my-trafficsplit-svc2
      port: 8080
      weight: 7
```

- But as per https://github.com/kubernetes-sigs/gateway-api/issues/67, hostnames does not need to be unique. So users can assume that the multiple HTTPRoute (the first example) is supported.
