### ISSUE TITLE
Unclear specification for a single host with weight=0 in HTTPRoute

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#596]
**What happened**:

As per spec comment:

https://github.com/kubernetes-sigs/gateway-api/blob/1caea70dce2571124a7a4887d32076ff8aa166e2/apis/v1alpha1/httproute_types.go#L624-L627

it seems that `weight = 0` for only one backend is not invalid but what error code is expected - 404, 503 or something else?
Also, a single host with `weight = 0` should be invalid configuration?

**How to reproduce it (as minimally and precisely as possible)**:

<details>
<summary>1. deploy Gateway,GatewayClass,HTTPRoute (with weight=0) ,Deployments</summary>

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-demo
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: GatewayClass
metadata:
  name: istio
spec:
  controller: istio.io/gateway-controller
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: simple-gateway
  namespace: gateway-demo
spec:
  gatewayClassName: istio
  listeners:  # Use GatewayClass defaults for listener definition.
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      namespaces:
        from: "All"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: gateway-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: whereami
        image: docker.io/kennethreitz/httpbin
        ports:
          - containerPort: 80
        env:
        - name: METADATA
          value: "foo"
---
apiVersion: v1
kind: Service
metadata:
  name: foo-svc
  namespace: gateway-demo
spec:
  selector:
    app: foo
  ports:
  - port: 8000
    targetPort: 80
---
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: test
  namespace: gateway-demo
spec:
  gateways:
    allow: SameNamespace
  hostnames:
  - "*"
  rules:
  - forwardTo:
    - port: 8000
      serviceName: foo-svc
      weight: 0
    matches:
    - path:
        type: Prefix
        value: /
EOF
```
</details>

2. Access to the service.

```
$ curl $IP:$PORT/headers -s -o /dev/null -w "%{http_code}" 
```

It is not clear what error code (`404` `503` or something else) the client gets.
