### ISSUE TITLE
Multipe HTTPRouteFilters with same type are supported?

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#598]
**What happened**:

Currently there are two ways of writing HTTPRouteFilter when we add two headers.

examp-a) Single filter with two headers.

```yaml
      filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
            first-header: foo
            second-header: bar
```

examp-b) Two filters with one header each.

```yaml
      filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
            first-header: foo
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
            second-header: bar
```

Both example-a and example-b are supported?

**What you expected to happen**:

- I just want to make sure the spec if both writing styles are supported.

**Anything else we need to know?**:

- If only example-a is supported, the implementation is simple. For example, istio has [this code](https://github.com/istio/istio/blob/b1810a6e9578c7063b437ebb6fc0755d45844b79/pilot/pkg/config/kube/gateway/conversion.go#L325-L332):

```go
		for _, filter := range r.Filters {
			switch filter.Type {
			case k8s.HTTPRouteFilterRequestHeaderModifier:
				vs.Headers = createHeadersFilter(filter.RequestHeaderModifier)
			default:
				log.Warnf("unsupported filter type %q", filter.Type)
			}
		}
```

- But example-b needs more code to merge the same type filters.
- I wonder some users will try to write example-b style as HTTPRouteMatch supports example-b style only. So it should be clear.

c.f. HTTPRouteMatch
```yaml
    - matches:
      - path:
          type: Prefix
          value: /first
      - path:
          type: Prefix
          value: /second
```
