### ISSUE TITLE
Method based routing

### ISSUE THREAD

**Issue by zoglesby** [kubernetes-sigs/gateway-api#624]
I did a quick search and did not see a ticket for this, if I missed it I am sorry.

**What would you like to be added**:
Method based routing would be a nice addition. This is something that we are currently looking to implement in another part of our stack, but having it in a gateway-api would make things easier for us.

An example of this can be found in Ambassador 

```
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: get
spec:
  prefix: /backend/get_only/
  method: GET
  service: quote
```
https://www.getambassador.io/docs/edge-stack/latest/topics/using/method/#method-based-routing

**Why is this needed**:
There are many use cases for this, but the my primary need for this is to split read (GET) and write (PUT) traffic to different endpoints.
