### ISSUE TITLE
Canary deployments with Gateway API between namespaces

### ISSUE THREAD

**Issue by arapulido** [kubernetes-sigs/gateway-api#695]
The Gateway API spec seems to expect each team to work on a single namespace, which feels a bit too rigid for certain use cases. 

In my case, I would like to be able to do canary deployments that involve services that are not directly getting external traffic. This is a lot easier to do if you can do a different deployment in a second namespace, something like this:

![image](https://user-images.githubusercontent.com/925437/122544568-3bc7fd00-d02d-11eb-9431-c67970de9713.png)

```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: httproute1
  namespace: ns1
  labels:
    app: ecommerce
spec:
  gateways:
    allow: "All"
  hostnames:
    - "www.example.org"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: service1
          port: 80
          weight: 50
```

```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: httproute2
  namespace: ns2
  labels:
    app: ecommerce
spec:
  gateways:
    allow: "All"
  hostnames:
    - "www.example.org"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: service1
          port: 80
          weight: 50
```

This is not currently possible with the current spec and something that will be useful to have (to put an example, the NGINX Ingress controller allows to do this).

Similar, I am wondering if this other way to implement the same thing is allowed by the spec:

![image](https://user-images.githubusercontent.com/925437/122545212-de807b80-d02d-11eb-91f5-b6454bcdec6b.png)

Basically, having a single HTTPRoute object, but that points to an ExternalService, pointing to the service in the second namespace

```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: httproute-external
  namespace: ns1
  labels:
    app: ecommerce
spec:
  gateways:
    allow: "All"
  hostnames:
    - "www.example.org"
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      forwardTo:
        - serviceName: service1
          port: 80
          weight: 50
        - serviceName: service1-external
          port: 80
          weight: 50
```

With `service1-external` looking like this:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: service1-external
spec:
  type: ExternalName
  externalName: service1.ns2.svc.cluster.local
```

**Comment by bowei** [comment]
We are currently discussion the addition of "inclusion" or "delegation" of HTTPRoute which may meet your criteria.

In your example, your HTTPRoute objects are the same -- how is this not the same as a simple traffic split?

```



    +-----------------+           +----------------+
    |                 |           |                |
    |  HTTPRoute   50%-------------> Service 1     |
    |              50%---------+  |                |
    +-----------------+        |  +----------------+
                               |  +----------------+
                               |  |                |
                               +-->> Service 2     |
                                  |                |
                                  +----------------+
```

**Comment by arapulido** [comment]
Sure, the difference would be that service 2 is on a different namespace, to make it easier to do traffic splits on whole applications, when the service that changes is not the first one.

These would be the `nginx` configs:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: ns1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: ns2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  rules:
  - host: www.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
```

**Comment by mark-church** [comment]
There are actually two active discussions about making this possible as a 1st class capability of the API. [This](https://docs.google.com/document/d/1_B1G9JcNw3skNYLtdK7lTTzOeyz5w2hpa84cKA_MGKk/edit?usp=sharing) is the proposal for cross-Namespace Route->Service (by @robscott) and [this](https://docs.google.com/document/d/1-0mgRRAY784OgGQ1_LCOshpLLbeAtIr4eXd0YVYK4RY/edit?usp=sharing)  is the proposal for cross-Namespace Route->Route (by @youngnick). Both are a bit early proposals but making steady progress. 

Today there can be a cross-Namespace relationship between Gateways and Routes but not between any other resources. There are several other cross-Namespace relationships that are very useful though.

![image](https://user-images.githubusercontent.com/17914385/125150321-873d6a80-e104-11eb-9699-5c6ed01e3203.png)

- Gateway-Route is useful when merging different Routes to the same Gateway, different teams that want full control of their routing config but want to share the same load balancer
- Route-Route is useful for Route delegation, or when a portion of the Route should be defined in one Namespace and sub-portion of it defined in another Namespace
- Route-Service is useful for having routing configured in different Namespace where the app is deployed (your use-case)
- Gateway-Secret is useful for when secrets shouldn't be accessed directly by the Gateway-owner. They can be referenced but not directly accessed.

The syntax could likely change and this is not in the API today, but your use-case could look something like the following. Here I've put the HTTPRoute in `ns1` while the Services are in `ns2` and `ns3`.

```yaml
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: cross-ns-route
  namespace: ns1
  labels:
    gateway: external-http
spec:
  hostnames:
    - "www.example.org"
  rules:
  - forwardTo:
    - serviceName: service1
      namespace: ns2
      port: 8080
      weight: 50
    - serviceName: service1
      namespace: ns3
      port: 8080
      weight: 90
```

@arapulido can I ask why you would like to do canaries between different Namespaces? Is this because it's simple to canary an entire stack because every service is using the same name within a Namespace?
