### ISSUE TITLE
Cross-namespace Route binding is mismatching of traefik 2.4.9 from traefik-helm-chart

### ISSUE THREAD

**Issue by hannius** [kubernetes-sigs/gateway-api#795]
the traefik helm chart github is: "https://github.com/traefik/traefik-helm-chart"
the traefik version is : 2.4.9
the gateway-api version is : v0.3.0
and traefik is under namespace: kube-system
the gatewayclass yaml is :
```
➜  templates git:(master) cat gatewayclass.yaml 
{{- if .Values.experimental.kubernetesGateway.enabled }}
---
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: traefik
spec:
  controller: traefik.io/gateway-controller
{{- end }}
```
and the gateway yaml is below:
```
➜  templates git:(master) cat gateway.yaml 
{{- if .Values.experimental.kubernetesGateway.enabled }}
--- 
apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata: 
  name: traefik-gateway
  namespace: {{ default .Release.Namespace .Values.experimental.kubernetesGateway.namespace }}
spec: 
  gatewayClassName: traefik
  listeners: 
    - port: {{ .Values.ports.web.port }}
      protocol: HTTP
      routes: 
        kind: HTTPRoute
        namespaces:
          from: All
        #selector: 
        #  matchLabels: 
        #    app: {{ .Values.experimental.kubernetesGateway.appLabelSelector }}

    {{- range $index, $cert:= .Values.experimental.kubernetesGateway.certificates }}
    - port: {{ $.Values.ports.websecure.port }}
      protocol: HTTPS
      tls:
        certificateRef:
          name: {{ $cert.name }}
          group: {{ $cert.group }}
          kind: {{ $cert.kind }}
      routes: 
        kind: HTTPRoute
        namespaces:
          from: All
        #selector: 
        #  matchLabels: 
        #    app: {{ $.Values.experimental.kubernetesGateway.appLabelSelector }}
    {{- end }}
{{- end }}
```
➜  traefik_new git:(master) helm install traefik-test --namespace kube-system -f values_diymaster.yaml --debug .

-------------------------------------------------------------------------------------------------------------------------------

the application app httproute is under the namespace: martin
and the name is app, corresponding httproute yaml is below:
```
➜  templates git:(master) cat httproute.yaml 
{{- if .Values.httproute.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: {{ template "app.fullname" . }}-httproute
  namespace: {{ default .Release.Namespace .Values.httproute.namespace }}
  #labels:
  #  app: {{ .Values.httproute.appLabelSelector }}
spec:
  gateways:
    allow: All
    #allow: FromList
    #gatewayRefs:
    #- name: {{ .Values.httproute.gateway_name }}
    #  namespace: {{ .Values.httproute.gateway_namespace }}
  hostnames:
  - {{ .Values.httproute.hostnames }}
  rules:
  - matches:
    - path:
        #type: Exact
        type: Prefix
        value: /
    forwardTo:
    - serviceName: {{ $fullName }}
      port: {{ $svcPort }}
      weight: 1
{{- end }}
```

the values.yaml is below:
```
...
httproute:
  enabled: true
  hostnames: martin-test.century.com
  namespace: martin
  gateway_name: traefik-gateway
  gateway_namespace: kube-system
  #namespace: kube-system
  appLabelSelector: traefik
...
```
➜  martin git:(master) helm install martin-test --namespace martin -f values_test.yaml --debug . 

the Component status is ok:
```
➜  traefik_new git:(master) kubectl get gatewayclasses.networking.x-k8s.io --all-namespaces
NAME      CONTROLLER                      AGE
traefik   traefik.io/gateway-controller   35m
➜  traefik_new git:(master) kubectl get gateways.networking.x-k8s.io --all-namespaces
NAMESPACE     NAME              CLASS     AGE
kube-system   traefik-gateway   traefik   36m
➜  traefik_new git:(master) kubectl get httproutes.networking.x-k8s.io --all-namespaces -o wide
NAMESPACE          NAME                                 HOSTNAMES                       AGE
martin   martin-test-httproute   [martin-test.century.com]   41m
➜  traefik_new git:(master) 
```

from the dashboard i can see the KubernetesGateway Providers is On, but the martin-httproute created by me is just invisible
![image](https://user-images.githubusercontent.com/18302266/130210006-51f4383a-d3d5-4750-9bce-9bec2da5561f.png)
![image](https://user-images.githubusercontent.com/18302266/130213877-cb20f805-084b-4ae9-ba2e-e766ca09e493.png)

the traefik error logs is : 
![image](https://user-images.githubusercontent.com/18302266/130217302-4c516819-086d-47b5-9c9f-728eae99445b.png)

and when i access the url, it return the 404 Error,so i can realize the route will not be matched.

But when i changed the httproute namespace to kube-system that is the same of traefik，i found it ok.
```
➜  martin git:(master) helm install martin-test --namespace martin -f values_test.yaml --debug .
➜  martin git:(master) kubectl get httproutes.networking.x-k8s.io --all-namespaces -o wide
NAMESPACE     NAME                                 HOSTNAMES                       AGE
kube-system   martin-test-httproute   [martin-test.century.com]   107s
```
![image](https://user-images.githubusercontent.com/18302266/130213391-d00b9eb6-037d-41a4-af05-68171a33c7ea.png)

so Whether the gatewayapi does not support cross-namespace? could you help me to solve the problem, thanks very much.
