### ISSUE TITLE
failed to assign to any requested addresses: Only NamedAddress is supported, ignoring [192.168.198.194]

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-sigs/gateway-api#799]
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  addresses:
  - type: IPAddress
    value: 192.168.198.194
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute
```
