### ISSUE TITLE
hostname *.demo  got 404

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-sigs/gateway-api#800]
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*.demo"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute
```
