### ISSUE TITLE
gateway namespace same,httproute in the same namesapce,but svc in different namespace,got 503

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-sigs/gateway-api#801]
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: Same
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute
      group: networking.x-k8s.io
```
```
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: All
  hostnames: ["*"]
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage.istio.svc.cluster.local
      port: 9080
```
HTTP ERROR 503
[2021-08-22T07:59:01.989Z] "GET /productpage HTTP/1.1" 503 NC cluster_not_found - "-" 0 0 0 - "172.20.0.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "bede6911-acef-4b6f-a223-bf8c02ebf100" "bookinfo.demo:30902" "-" - - 172.20.1.151:8080 172.20.0.0:59367 - -
