### ISSUE TITLE
gateway routes matchExpressions visite page got 404

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-sigs/gateway-api#802]
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchExpressions:
        - key: gateway
          operator: in
          values:
          - bookinfo
      kind: HTTPRoute
      group: networking.x-k8s.io
```
```
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: All
  hostnames: ["*"]
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage.istio.svc.cluster.local
      port: 9080
```
