### ISSUE TITLE
what options does gateway tls support , my enviroment is istio?

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-sigs/gateway-api#805]
```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 443
    protocol: HTTPS
    tls:
      options: 
        xx: yy
      mode: Terminate
      certificateRef:
        name: bookinfo-gateway-secret
        kind: Secret
        group: core
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute
```
the validate did not validate this options field
