### ISSUE TITLE
httproute hostname *.demo got 404,enviroment istio

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-sigs/gateway-api#806]
```
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: productpage
  labels:
    gateway: bookinfo
spec:
  gateways:
    allow: All
  hostnames: ["*.demo"] 
  rules:
  - matches:
    - path:
        type: Prefix
        value: /productpage
    - path:
        type: Prefix
        value: /static
    forwardTo:
    - serviceName: productpage
      port: 9080
```

```
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: bookinfo
spec:
  gatewayClassName: istio
  listeners:  
  - hostname: "*"
    port: 80
    protocol: HTTP
    routes:
      namespaces:
        from: All
      selector:
        matchLabels:
          gateway: bookinfo
      kind: HTTPRoute
```
