### ISSUE TITLE
GEP: Add HTTPRouteFilterTemplates at the gateway level

### ISSUE THREAD

**Issue by TeoGoddet** [kubernetes-sigs/gateway-api#997]
**What would you like to be added**:
Possibilty to define `HTTPRouteFilterTemplates` at the gateway level, that could be used in the routes juste by calling their names.

Something like this : 
```
httpRouteFilterTemplates: ([HTTPRouteFilterTemplate])
   - name: my-sample-gateway-filter (String)
     HTTPRouteFilterSpec: (HTTPRouteFilterType)
     enableByDefault: false (Bool)
     forceEnable: false (Bool)

```
`enableByDefault` and `forceEnable` can be discussed separatly

Then one could add some `HTTPRouteFilter` of type `GatewayTemplate` in route rule definitions : 
```
filters:
 - type: GatewayTemplate
   GatewayTemplate:
     name: my-sample-gateway-filter
```
   

**Why this is needed**:

- allow to avoid a lot of redundancy in the filter definition
- allow clusterOperator to give app owner ready made filters (auth, security, tracing, ...)
- allow clusterOperator to ensure a filter is applied on a whole gateway (this part can be discussed as a second issue)

**Comment by TeoGoddet** [comment]
I had this idea while thinking at the traefik implementation for HTTPRouteFilter as TraefikMiddleware.
See https://github.com/traefik/traefik/issues/8705

**Comment by howardjohn** [comment]
I feel like this is the place https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/ can shine. It does blur the line between 'policy' and 'filters' - IMO they are essentially two ways in the API to achieve the same things.

For example, in this use case you would have some something like:
```
kind: Tracing
spec:
  targetRef:
    kind: Gateway
    name: my-gw
  tracingConfig: { ...}
```
